### ISSUE TITLE
[nuxt-i18n] Failed loading async locale export: globals.Headers is not a constructor

### ISSUE THREAD

**Issue by florian-lefebvre** [nuxt-modules/i18n#1123]
I try to deploy a Nuxt SSR app to Vercel but I'm facing issues.
I'm fetching my locales during the build, so here is my `nuxt.config.js` file:
```js
import localesFetcher from "./lang/localesFetcher";

export default async function () {
  const locales = await localesFetcher();
  return {
    // a lot of stuff there
    i18n: {
      baseUrl: process.env.BASE_URL || "http://localhost:3000",
      strategy: "prefix",
      locales,
      lazy: true,
      langDir: "lang/",
      defaultLocale: "en",
      vueI18n: {
        fallbackLocale: "en",
      },
      detectBrowserLanguage: {
        useCookie: true,
        cookieKey: "i18n_redirected",
        onlyOnRoot: true,
      },
    },
  };
}
```

I know my locales object is correct because I log them in the console so no issue there.
However, when deployed on Vercel, my pages show "Nuxt Internal Server Error" and looking at functions in the dashboard, I have the following error:
```bash
2021-03-26T17:14:19.229Z	fe8356af-8b2b-458c-90f5-83792194905f	ERROR	[nuxt-i18n] Failed loading async locale export: globals.Headers is not a constructor
2021-03-26T17:14:19.230Z	fe8356af-8b2b-458c-90f5-83792194905f	DEBUG	Error occurred when calling nuxtServerInit:  globals.Headers is not a constructor
 ERROR  globals.Headers is not a constructor
  at mergeHeaders (node_modules_dev/ky/index.js:52:0)
  at deepMerge (node_modules_dev/ky/index.js:88:0)
  at validateAndMerge (node_modules_dev/ky/index.js:509:0)
  at Function.ky.<computed> [as post] (node_modules_dev/ky/index.js:516:0)
  at http_HTTP.module.exports.http_HTTP.<computed> [as post] (.nuxt/http.js:95:0)
  at http_HTTP.module.exports.http_HTTP.<computed> [as $post] (.nuxt/http.js:126:0)
  at strapi_Strapi.graphql (node_modules_dev/@nuxtjs/strapi/lib/runtime/strapi.js:122:0)
  at Store.update (store/api.js:17:0)
  at Array.wrappedActionHandler (node_modules_dev/vuex/dist/vuex.common.js:853:0)
  at Store.dispatch (node_modules_dev/vuex/dist/vuex.common.js:518:0)
```
I don't know what to do with that now.

**Comment by rchl** [comment]
The problem is most likely not in this part of the code but in the function that loads the translations (referenced by locale's `file` property).

`globals.Headers is not a constructor` is a code from `ky`. I can see that the latest version of `ky` has now changed this code a bit so maybe try updating to the latest version.

**Comment by florian-lefebvre** [comment]
Ok so it's related with the strapi module, thx for your help!
