### ISSUE TITLE
[Nuxt 3 RC-1] Error on build

### ISSUE THREAD

**Issue by darthf1** [nuxt-modules/i18n#1428]
### Version
@nuxtjs/i18n: npm:@nuxtjs/i18n-edge 8d5d96492ec381b60eb179bcc13689f644738692
nuxt: v3.0.0-rc.1
pnpm 6.32.9

----

Hi!

I wanted to see how far I could go migrating Nuxt 2 to Nuxt 3 RC. During build, I got an error related to `nuxt-i18n`. Feel free to close if this is because the repository is still WIP.

I got:
```
 ERROR  [vite-plugin-vue-i18n] Cannot read properties of undefined (reading 'message')                                                                                                                                15:16:52
file: /home/xxx/www/analytikal/client/translations/en.json


 ERROR  Cannot read properties of undefined (reading 'message')                                                                                                                                                       15:16:52

  at Object.newOptions.onError (node_modules/@intlify/bundle-utils/lib/codegen.js:102:48)
  at Object.newOptions.onError (node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
  at newOptions.onError (node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
  at emitError (node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:196:13)
  at readTokenInLinked (node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:745:21)
  at readToken (node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:759:20)
  at Object.nextToken (node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:801:16)
  at parseLinked (node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:936:31)
  at parseMessage (node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:1035:36)
  at parseResource (node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:1074:25)
```

`nuxt.config.ts`
```ts
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  modules: ['@nuxtjs/i18n'],

  i18n: {
    defaultLocale: 'nl',
    detectBrowserLanguage: false,
    locales: [
      { code: 'nl', name: 'Nederlands', file: 'nl.json' },
      { code: 'en', name: 'Engels', file: 'en.json' },
    ],
    vueI18n: {
      fallbackLocale: 'nl',
    },
    lazy: true,
    langDir: 'translations/',
  },
})

```

**Comment by Rigo-m** [comment]
I too can't load locales on nuxt 3 rc1/2/3.
I guess there are some errors with `addTemplate` calls not using the `write: true` option. Routing works, locales and fallback locales seems to work, but messages in `.json` files are not working.
@kazupon this module would be usable for a project if this feature work, are you able to provide help anyhow?

**Comment by rchl** [comment]
According to the referenced commit above, the `write: true` was added.
