### ISSUE TITLE
[Nuxt Bridge] [vite]: Rollup failed to resolve import

### ISSUE THREAD

**Issue by darthf1** [nuxt-modules/i18n#1430]
### Version
@nuxtjs/i18n: 7.2.1
nuxt: 2.15.8

### Nuxt configuration

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [X] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```js
{
  i18n: {
    defaultLocale: 'nl',
    detectBrowserLanguage: false,
    parsePages: true,
    locales: [
      { code: 'nl', name: 'Nederlands', file: 'nl.json' },
      { code: 'en', name: 'Engels', file: 'en.json' },
    ],
    vueI18n: {
      fallbackLocale: 'nl',
    },
    vueI18nLoader: true,
    lazy: true,
    langDir: 'translations/',
  },
}
```

Hi!

I'm trying to see If I can migrate to Nuxt Bridge. Upon build, I get an error that the import `nuxti18n` middleware is failed to resolve. I have no middleware related to or named `nuxti18n`, so I guess its related to this module.

I'm not sure if this is a bug in this module which surfaces with Nuxt Bridge, or if this is a bug in Nuxt Bridge itself.

```
 Building client...
 ERROR  [vite]: Rollup failed to resolve import "/home/node/app/middleware/nuxti18n" from ".nuxt/middleware.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
 ERROR  [vite]: Rollup failed to resolve import "/home/node/app/middleware/nuxti18n" from ".nuxt/middleware.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  at onRollupWarning (node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:39256:19)
  at onwarn (node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:39072:13)
  at Object.onwarn (node_modules/rollup/dist/shared/rollup.js:23173:13)
  at ModuleLoader.handleResolveId (node_modules/rollup/dist/shared/rollup.js:22463:26)
  at node_modules/rollup/dist/shared/rollup.js:22424:26
```

**Comment by divine** [comment]
Hello,

The current stable version isn't compatible with the bridge. You need to wait until the `next` branch will be ready.

Thanks!

**Comment by rchl** [comment]
See https://github.com/nuxt-community/i18n-module/issues/1410
