### ISSUE TITLE
ERROR with resolveAlias

### ISSUE THREAD

**Issue by Duvalu2017** [nuxt-modules/i18n#1442]
I am using Nuxt 3

ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'resolveAlias')                                                                                        20:34:35

  at Object._default (node_modules/@nuxtjs/i18n/src/index.js:34:42)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:392:20)
  at async initNuxt (node_modules/nuxt3/dist/index.mjs:1353:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6734:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6777:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)

**Comment by portlek** [comment]
it does not support nuxt 3.

**Comment by rchl** [comment]
https://github.com/nuxt-community/i18n-module/issues/1410
