### ISSUE TITLE
Error compiling template

### ISSUE THREAD

**Issue by Kingside88** [nuxt-modules/i18n#1449]
### Version
@nuxtjs/i18n: 7.2.2
nuxt: 3.0.0-rc.3

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ ] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
I followed the basic configuration: https://i18n.nuxtjs.org/setup
```
  i18n: {
    locales: ['en', 'fr', 'es'],
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        en: {
          welcome: 'Welcome'
        },
        fr: {
          welcome: 'Bienvenue'
        },
        es: {
          welcome: 'Bienvenido'
        }
      }
    }
  },
```
-->

### What is actually happening?
 ERROR  Error compiling template:  {                                                                                                          17:17:37  
  src: 'xxx\\node_modules\\@nuxtjs\\i18n\\src\\templates\\head-meta.js',
  fileName: 'nuxt-i18n\\head-meta.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object],
      REDIRECT_ON_OPTIONS: [Object]
    },
    nuxtOptions: {
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [Array],
      localeCodes: [Array]
    }
  },
  write: true,
  filename: 'nuxt-i18n\\head-meta.js',
  dst: 'xxx/.nuxt/nuxt-i18n/head-meta.js'
}

**Comment by ndom91** [comment]
Also getting this error. It originally happened on an old windows 7 machine of mine I was using temporarily. Only had node 14 so I figured widnows / old versin of node was at fault.

So i tried it in a github codespace with node 16, same error. Full output below.

It seems to fail to compile a few files in `.nuxt/nuxt-i18n` after runnin ginto a `requireModule is not defined`.

Also using:

```
@nuxtjs/i18n: 7.2.2
nuxt: 3.0.0-rc.3
```

<details><summary>Error output</summary>

```
ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'requireModule')                                          12:19:42

  at node_modules/@nuxtjs/i18n/src/core/hooks.js:25:51
  at node_modules/@nuxt/kit/dist/index.mjs:495:37
  at node_modules/hookable/dist/index.mjs:39:70
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.getContents (node_modules/nuxt/dist/index.mjs:354:9)
  at async node_modules/nuxt/dist/index.mjs:1562:22
  at async Promise.all (index 20)
  at async generateApp (node_modules/nuxt/dist/index.mjs:1561:3)
  at async _applyPromised (node_modules/perfect-debounce/dist/index.mjs:54:10)


 ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'requireModule')                                         12:19:42

  at node_modules/@nuxtjs/i18n/src/core/hooks.js:25:51
  at node_modules/@nuxt/kit/dist/index.mjs:495:37
  at node_modules/hookable/dist/index.mjs:39:70
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.getContents (node_modules/nuxt/dist/index.mjs:354:9)
  at async node_modules/nuxt/dist/index.mjs:1562:22
  at async Promise.all (index 20)
  at async generateApp (node_modules/nuxt/dist/index.mjs:1561:3)
  at async _applyPromised (node_modules/perfect-debounce/dist/index.mjs:54:10)


 ERROR  Error compiling template:  {                                                                                               12:19:42
  src: '/workspaces/chalet-allegro/node_modules/@nuxtjs/i18n/src/templates/head-meta.js',
  fileName: 'nuxt-i18n/head-meta.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object],
      REDIRECT_ON_OPTIONS: [Object]
    },
    nuxtOptions: {
      isUniversalMode: false,
      trailingSlash: undefined
    },
    options: {
      vueI18n: [Object],
      vueI18nLoader: false,
      locales: [Array],
      defaultLocale: 'en',
      defaultDirection: 'ltr',
      routesNameSeparator: '___',
      defaultLocaleRouteNameSuffix: 'default',
      sortRoutes: true,
      strategy: 'prefix_except_default',
      lazy: false,
      langDir: null,
      rootRedirect: null,
      detectBrowserLanguage: [Object],
      differentDomains: false,
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [Array],
      localeCodes: [Array]
    }
  },
  write: true,
  filename: 'nuxt-i18n/head-meta.js',
  dst: '/workspaces/chalet-allegro/.nuxt/nuxt-i18n/head-meta.js'
}


 ERROR  Error compiling template:  {                                                                                               12:19:42
  src: '/workspaces/chalet-allegro/node_modules/@nuxtjs/i18n/src/templates/plugin.main.js',
  fileName: 'nuxt-i18n/plugin.main.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object],
      REDIRECT_ON_OPTIONS: [Object]
    },
    nuxtOptions: {
      isUniversalMode: false,
      trailingSlash: undefined
    },
    options: {
      vueI18n: [Object],
      vueI18nLoader: false,
      locales: [Array],
      defaultLocale: 'en',
      defaultDirection: 'ltr',
      routesNameSeparator: '___',
      defaultLocaleRouteNameSuffix: 'default',
      sortRoutes: true,
      strategy: 'prefix_except_default',
      lazy: false,
      langDir: null,
      rootRedirect: null,
      detectBrowserLanguage: [Object],
      differentDomains: false,
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [Array],
      localeCodes: [Array]
    }
  },
  filename: 'nuxt-i18n/plugin.main.js',
  dst: '/workspaces/chalet-allegro/.nuxt/nuxt-i18n/plugin.main.js'
}


 ERROR  Error compiling template:  {                                                                                               12:19:42
  src: '/workspaces/chalet-allegro/node_modules/@nuxtjs/i18n/src/templates/plugin.routing.js',
  fileName: 'nuxt-i18n/plugin.routing.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object],
      REDIRECT_ON_OPTIONS: [Object]
    },
    nuxtOptions: {
      isUniversalMode: false,
      trailingSlash: undefined
    },
    options: {
      vueI18n: [Object],
      vueI18nLoader: false,
      locales: [Array],
      defaultLocale: 'en',
      defaultDirection: 'ltr',
      routesNameSeparator: '___',
      defaultLocaleRouteNameSuffix: 'default',
      sortRoutes: true,
      strategy: 'prefix_except_default',
      lazy: false,
      langDir: null,
      rootRedirect: null,
      detectBrowserLanguage: [Object],
      differentDomains: false,
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [Array],
      localeCodes: [Array]
    }
  },
  filename: 'nuxt-i18n/plugin.routing.js',
  dst: '/workspaces/chalet-allegro/.nuxt/nuxt-i18n/plugin.routing.js'
}


 ERROR  Error compiling template:  {                                                                                               12:19:42
  src: '/workspaces/chalet-allegro/node_modules/@nuxtjs/i18n/src/templates/plugin.utils.js',
  fileName: 'nuxt-i18n/plugin.utils.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object],
      REDIRECT_ON_OPTIONS: [Object]
    },
    nuxtOptions: {
      isUniversalMode: false,
      trailingSlash: undefined
    },
    options: {
      vueI18n: [Object],
      vueI18nLoader: false,
      locales: [Array],
      defaultLocale: 'en',
      defaultDirection: 'ltr',
      routesNameSeparator: '___',
      defaultLocaleRouteNameSuffix: 'default',
      sortRoutes: true,
      strategy: 'prefix_except_default',
      lazy: false,
      langDir: null,
      rootRedirect: null,
      detectBrowserLanguage: [Object],
      differentDomains: false,
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [Array],
      localeCodes: [Array]
    }
  },
  filename: 'nuxt-i18n/plugin.utils.js',
  dst: '/workspaces/chalet-allegro/.nuxt/nuxt-i18n/plugin.utils.js'
}


 ERROR  Error compiling template:  {                                                                                               12:19:42
  src: '/workspaces/chalet-allegro/node_modules/@nuxtjs/i18n/src/templates/utils-common.js',
  fileName: 'nuxt-i18n/utils-common.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object],
      REDIRECT_ON_OPTIONS: [Object]
    },
    nuxtOptions: {
      isUniversalMode: false,
      trailingSlash: undefined
    },
    options: {
      vueI18n: [Object],
      vueI18nLoader: false,
      locales: [Array],
      defaultLocale: 'en',
      defaultDirection: 'ltr',
      routesNameSeparator: '___',
      defaultLocaleRouteNameSuffix: 'default',
      sortRoutes: true,
      strategy: 'prefix_except_default',
      lazy: false,
      langDir: null,
      rootRedirect: null,
      detectBrowserLanguage: [Object],
      differentDomains: false,
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [Array],
      localeCodes: [Array]
    }
  },
  write: true,
  filename: 'nuxt-i18n/utils-common.js',
  dst: '/workspaces/chalet-allegro/.nuxt/nuxt-i18n/utils-common.js'
}
```
</details>

**Comment by stafyniaksacha** [comment]
You may want to try the edge release: https://github.com/nuxt-community/i18n-module/discussions/1287

**Comment by rchl** [comment]
See https://github.com/nuxt-community/i18n-module/issues/1410

**Comment by FrancoLab** [comment]
Any solution to this? sitting with the exact same problem

**Comment by biniyammoges** [comment]
having the same issue, any solution yet?

**Comment by luccabassan** [comment]
Any solution to this?

**Comment by biniyammoges** [comment]
> Any solution to this?

I think it's version incompatibility and I instead used `@intlify/nuxt3` package and it worked for me

**Comment by RodrigoBlanco** [comment]
Hi! I have the same issue. It´s there any solution?

**Comment by biniyammoges** [comment]
> Hi! I have the same issue. It´s there any solution?

You can use package `@intlify/nuxt3`, it works with nuxt3

**Comment by mariebehzadi** [comment]
> > Hi! I have the same issue. It´s there any solution?
> 
> You can use package `@intlify/nuxt3`, it works with nuxt3

unfortunately `@intlify/nuxt3` doesn't support automatic localized routes at this stage. a good sample to solve this problem is described [here](https://github.com/nuxt-community/i18n-module/issues/1410#issuecomment-1192735679)
