### ISSUE TITLE
How to import useI18n and useLocalePath composables in Nuxt3

### ISSUE THREAD

**Issue by dergunovs** [nuxt-modules/i18n#1456]
Hi. Firstly, i want to thank you for your great work on this package.

I'm using nuxt3 rc4 (with rc3 the errors were the same) and @nuxtjs/i18n-edge 8.0.0-alpha.0-27579558.fdbd51b
Package.json dependencies section is very simple:
```
"dependencies": {
    "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.4"
  }
```
nuxt.config.ts was inspired by your example here https://github.com/nuxt-community/i18n-module/blob/next/playground/nuxt3/nuxt.config.ts

```
import { defineNuxtConfig } from "nuxt";

export default defineNuxtConfig({
  modules: ["@nuxtjs/i18n"],

  vite: { build: { minify: false } },

  i18n: {
    langDir: "locales",
    lazy: true,
    baseUrl: "http://localhost:3000",
    locales: [
      { code: "ru", iso: "ru-RU", file: "ru.json", name: "ru" },
      { code: "en", iso: "en-US", file: "en.json", name: "en" },
    ],
    defaultLocale: "ru",
    detectBrowserLanguage: false,
    vueI18n: {
      legacy: false,
      locale: "ru",
      fallbackLocale: { ru: ["en"], en: ["ru"] },
    },
  },
});
```
I'm using useI18n and useLocalePath composables in pages and components. I'm importing composables like this:

```
  import { useI18n } from "@nuxtjs/i18n/node_modules/@intlify/vue-i18n-bridge";
  import { useLocalePath } from "@nuxtjs/i18n/node_modules/vue-i18n-routing";
```
In your playground example it is not very clear to understand where to import they from.
https://github.com/nuxt-community/i18n-module/blob/next/playground/nuxt3/pages/index.vue - here you import they from "#i18n". I tried to import them from "@nuxtjs/i18n", but:

`Module '"@nuxtjs/i18n"' has no exported member 'useI18n'.`

**What is the correct way to import them?**

**Comment by alexan059** [comment]
I wrote a support file, since this plugin is still under development and I couldn't find any documentation as well.

```ts
// utils/i18n-support.ts
import { ComputedRef } from 'vue';
import { Composer } from 'vue-i18n';
import { LocaleObject } from 'vue-i18n-routing';

export { useI18n } from 'vue-i18n';

export {
  useLocalePath,
  useSwitchLocalePath,
  useRouteBaseName,
  useLocaleRoute,
  useLocaleLocation,
  useLocaleHead,
} from 'vue-i18n-routing';

declare module 'vue-i18n' {
  export interface Composer {
    // added through @nuxtjs/i18n
    locales: ComputedRef<LocaleObject[]>;
  }
}
```

Then use it like:
```ts
import { useLocalePath } from '~/utils/i18n-support.ts';

const localePath = useLocalePath();
```


It works in development, but in a production build I get those errors, because of `useLocalePath`:

```
SyntaxError: 17
    at of (entry-9b8ba92c.mjs:23:69)
    at lt (entry-9b8ba92c.mjs:35:50)
    at Pr (entry-9b8ba92c.mjs:35:9202)
    at ab (entry-9b8ba92c.mjs:39:9077)
    at setup (entry-9b8ba92c.mjs:41:1352)
    at Kt (entry-9b8ba92c.mjs:1:12594)
    at xp (entry-9b8ba92c.mjs:1:58202)
    at Cp (entry-9b8ba92c.mjs:1:57987)
    at ct (entry-9b8ba92c.mjs:1:45013)
    at f (entry-9b8ba92c.mjs:1:39339)
xd @ entry-9b8ba92c.mjs:1
entry-9b8ba92c.mjs:1 TypeError: r.localePath is not a function
    at Proxy.g0 (entry-9b8ba92c.mjs:41:1703)
    at Ko (entry-9b8ba92c.mjs:1:15819)
    at Ee (entry-9b8ba92c.mjs:1:45887)
    at fs.T [as fn] (entry-9b8ba92c.mjs:1:45975)
    at fs.run (entry-9b8ba92c.mjs:1:4469)
    at de (entry-9b8ba92c.mjs:1:46272)
    at ct (entry-9b8ba92c.mjs:1:45110)
    at f (entry-9b8ba92c.mjs:1:39339)
    at d (entry-9b8ba92c.mjs:1:40499)
    at u (entry-9b8ba92c.mjs:1:40197)
xd @ entry-9b8ba92c.mjs:1
entry-9b8ba92c.mjs:1 SyntaxError: 17
    at of (entry-9b8ba92c.mjs:23:69)
    at lt (entry-9b8ba92c.mjs:35:50)
    at Pr (entry-9b8ba92c.mjs:35:9202)
    at setup (entry-9b8ba92c.mjs:41:1892)
    at Kt (entry-9b8ba92c.mjs:1:12594)
    at xp (entry-9b8ba92c.mjs:1:58202)
    at Cp (entry-9b8ba92c.mjs:1:57987)
    at ct (entry-9b8ba92c.mjs:1:45013)
    at ae (entry-9b8ba92c.mjs:1:44903)
    at g (entry-9b8ba92c.mjs:1:41742)
xd @ entry-9b8ba92c.mjs:1
entry-9b8ba92c.mjs:1 TypeError: r.t is not a function
    at Proxy.y0 (entry-9b8ba92c.mjs:41:2041)
    at Ko (entry-9b8ba92c.mjs:1:15819)
    at fs.T [as fn] (entry-9b8ba92c.mjs:1:46004)
    at fs.run (entry-9b8ba92c.mjs:1:4469)
    at de (entry-9b8ba92c.mjs:1:46272)
    at ct (entry-9b8ba92c.mjs:1:45110)
    at ae (entry-9b8ba92c.mjs:1:44903)
    at g (entry-9b8ba92c.mjs:1:41742)
    at z (entry-9b8ba92c.mjs:1:43252)
    at A (entry-9b8ba92c.mjs:1:42532)
```

So there must be a better solution...

**Comment by dergunovs** [comment]
> 

My imports in dev mode also working. And in production i have the same errors.

**Comment by alexan059** [comment]
Apparently, the correct way to import those composables is to use `import { useI18n } from "#i18n"`, as I could find in the examples in https://github.com/nuxt-community/i18n-module/issues/1451. The type recognition seems to be broken and it shows that it can't find the declarations, but it is still working in dev/prod.

**Comment by dergunovs** [comment]
> Apparently, the correct way to import those composables is to use `import { useI18n } from "#i18n"`, as I could find in the examples in #1451. The type recognition seems to be broken and it shows that it can't find the declarations, but it is still working in dev/prod.

No changes with "#i18n". Same errors in prod. Maybe you have a working example of the correct using of aplha version?

```
SyntaxError: 18
    at createCompileError (entry-9ee79e18.mjs:9810:18)
    at createI18nError (entry-9ee79e18.mjs:10778:10)
    at useI18n (entry-9ee79e18.mjs:11924:11)
    at setup (entry-9ee79e18.mjs:15733:27)

entry-9ee79e18.mjs:1105 TypeError: $setup.localePath is not a function
    at Proxy._sfc_render$7 (entry-9ee79e18.mjs:15112:24)

entry-9ee79e18.mjs:1105 TypeError: $setup.t is not a function
    at Proxy._sfc_render (index-31ba006a.mjs:197:60)
```

**Comment by alexan059** [comment]
It seems to be an ongoing issue at the latest alpha version. Try out this version in your `package.json`:

```json
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge@8.0.0-alpha.0-27531750.4e4cffe",
```

This is working for me and I will keep using it until the issue is solved: https://github.com/nuxt-community/i18n-module/issues/1451.

**Comment by dergunovs** [comment]
> 

Thank you so much! You saved my day :)
