### ISSUE TITLE
Error. Cannot read properties of undefined (reading 'resolveAlias')

### ISSUE THREAD

**Issue by aaliboyev** [nuxt-modules/i18n#1477]
### Version
@nuxtjs/i18n: ^7.2.3
nuxt: 3.0.0-rc.6

### Nuxt configuration

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```
{
    defaultLocale: 'en',
    locales: [
        { code: 'en', iso: 'en-US', file: 'en.js'},
        { code: 'ru', iso: 'ru-RU', file: 'ru.js'},
        { code: 'uz', iso: 'uz-UZ', file: 'uz.js'}
    ],
    langDir: './src/locales/',
    strategy: 'no_prefix',
    detectBrowserLanguage: {
        useCookie: true,
        cookieKey: 'i18n_redirected',
        onlyOnRoot: true  // recommended
    },
    seo: true,
    lazy: true,
    vueI18nLoader: true
}
```
### Steps to reproduce
`package.json` file
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@intlify/nuxt3": "^0.2.3",
    "@nuxtjs/tailwindcss": "^5.3.1",
    "nuxt": "3.0.0-rc.6"
  },
  "dependencies": {
    "@nuxt/types": "^2.15.8",
    "@nuxtjs/i18n": "^7.2.3",
    "@vueuse/core": "^9.0.2",
    "axios": "^0.27.2",
    "postcss-custom-properties": "^12.1.8",
    "sass": "^1.54.0",
    "sass-loader": "^13.0.2"
  }
}

```
### What is actually happening?
failing on build time with the error below
```
ERROR  Cannot restart nuxt:  Cannot read properties of undefined (reading 'resolveAlias')                                                                                                                                    17:21:24

  at Object._default (node_modules/@nuxtjs/i18n/src/index.js:34:42)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:432:20)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1421:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6750:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6693:10)
```

**Comment by rchl** [comment]
There is a WIP branch with Nuxt 3 support - https://github.com/nuxt-community/i18n-module/tree/next
