### ISSUE TITLE
Can't install via yarn

### ISSUE THREAD

**Issue by benwalsh** [nuxt-modules/i18n#1478]
### Steps to reproduce
In `package.json` add the reference as specified:

```
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",
```

and run `yarn` on the command line.

### What is Expected?

The package should be installed.

### What is actually happening?

It fails to find the package:

```
YN0000: ┌ Resolution step
➤ YN0001: │ Error: @nuxtjs/i18n@npm:@nuxtjs/i18n-edge isn't supported by any available resolver
    at wd.getResolverByDescriptor (/PATH/.yarn/releases/yarn-3.2.0.cjs:395:1664)
    at wd.bindDescriptor (/PATH/.yarn/releases/yarn-3.2.0.cjs:395:1053)
    at Z (/PATH/.yarn/releases/yarn-3.2.0.cjs:441:6953)
```

**Comment by rchl** [comment]
Seems to work for me:

```
❯ cat package.json
{
  "name": "test-yarn",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
  }
}

❯ yarn
yarn install v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@nuxtjs/i18n > vue-i18n@9.2.0-beta.40" has unmet peer dependency "vue@^3.0.0".
warning "@nuxtjs/i18n > vue-i18n-routing > vue-demi@0.13.6" has unmet peer dependency "vue@^3.0.0-0 || ^2.6.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 2.34s.
```

```
❯ yarn --version
1.22.19
```

**Comment by rchl** [comment]
Judging from your error message it seems to be the non-stable 3.x yarn. In that case maybe it doesn't implement that feature yet. You should ask at yarn's repo.
