### ISSUE TITLE
[next] Cannot read properties of undefined (reading 'currentRoute')

### ISSUE THREAD

**Issue by melrefaie** [nuxt-modules/i18n#1489]
### Version
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
"nuxt": "^3.0.0-rc.8"

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ ] Applies to a site deployed to a server with a Node backend

### What is actually happening?
I got this issue after updating @nuxtjs/i18n-edge  

I think its related to 
[https://github.com/nuxt-community/i18n-module/commit/ae3acd73d4423239fe47a0d88941ca4f2db21e6e](url)

```
vue-i18n-routing.mjs:704 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'currentRoute')
    at vue-i18n-routing.mjs:704:21
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at ReactiveEffect.getter [as fn] (runtime-core.esm-bundler.js:1729:24)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at doWatch (runtime-core.esm-bundler.js:1828:16)
    at watchEffect (runtime-core.esm-bundler.js:1649:12)
    at Lt (vue-i18n-routing.mjs:703:17)
    at setup (default.vue:19:21)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)

```

**Comment by kazupon** [comment]
Currently, @nuxtjs/i18n has been released v8 beta.
if you would have still issue, please open the new issue.

thanks!
