### ISSUE TITLE
[NEXT] Cannot start nuxt:  Cannot find module '@intlify/vue-i18n-bridge/lib/index.mjs'  

### ISSUE THREAD

**Issue by StefanVDWeide** [nuxt-modules/i18n#1535]
### Version
@nuxtjs/i18n: npm:@nuxtjs/i18n-edge
nuxt: 3.0.0-rc.11

### Nuxt configuration

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration
```
i18n: {
        baseUrl: 'https://studioterabyte.nl',
        locales: [
            {
                code: 'en',
                iso: 'en-US',
                file: 'en-US.json'
            },
            {
                code: 'nl',
                iso: 'nl-NL',
                file: 'nl-NL.json'
            }
        ],
        lazy: true,
        langDir: 'locales/',
        defaultLocale: 'nl',
        vueI18n: {
            legacy: false,
            fallbackLocale: 'nl',
            locale: 'nl'
        }
    },
```

### Steps to reproduce
Running `npm run dev` with the latest edge version installed will generate the following error:

```
 ERROR  Cannot start nuxt:  Cannot find module '@intlify/vue-i18n-bridge/lib/index.mjs'                         14:02:53
Require stack:
- /Users/stefan/Coding/studio-terabyte-website-nuxt-3/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:243257)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:261:29)
  at setupAlias (node_modules/@nuxtjs/i18n/dist/module.mjs:67:52)
  at setup (node_modules/@nuxtjs/i18n/dist/module.mjs:400:11)
  at async Object.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:637:5)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:456:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1606:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6778:9)
```

### What is Expected?
For Nuxt to resolve the expected imports needed for i18n.

### What is actually happening?
Nuxt can't resolve the  `@intlify/vue-i18n-bridge/lib/index.mjs` import needed for i18n and then errors out both when running the dev server and when generating a static page.

**Comment by StefanVDWeide** [comment]
Updating to the alpha.2 version seems to have resolved this.
