### ISSUE TITLE
<i18n global> does not work

### ISSUE THREAD

**Issue by MusicOnline** [nuxt-modules/i18n#1628]
### Version
@nuxtjs/i18n: Edge 0a3c92a
nuxt: 3.0.0-rc.13

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### Reproduction Link
Reproducible on minimal set up with the below snippet.

### Steps to reproduce
Add this to any SFC:
```vue
<i18n global lang="json">
{
  "en-US": {
    "locale": {
      "en": "English",
      "ja": "Japanese"
    }
  },
  "ja-JP": {
    "locale": {
      "en": "eigo",
      "ja": "nihongo"
    }
  }
}
</i18n>
```

### What is Expected?
Translations added to global scope. (either literal JSON or with src)

### What is actually happening?
Page does not load:
```
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'value')
    at adjustI18nResources (file:///project/.nuxt/dist/server/server.mjs:5970:56)
    at Module.useI18n (file:///project/.nuxt/dist/server/server.mjs:7967:9)
    at setup (file:///project/.nuxt/dist/server/server.mjs:52871:42)
    at _sfc_main.setup (file:///project/.nuxt/dist/server/server.mjs:52954:23)
    at callWithErrorHandling (project\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
    at setupStatefulComponent (project\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7135:29)
    at setupComponent (project\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7090:11)
    at renderComponentVNode (project\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:172:17)
    at Module.ssrRenderComponent (project\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:612:12)
    at default (file:///project/.nuxt/dist/server/server.mjs:52347:37)
```

**Comment by kazupon** [comment]
Thank you for your reproting!
I've faced this issue.

It might be the `@intlify/unplugin-vue-i18n` with using internally, so I'll more look up issues and then fix it!

**Comment by kazupon** [comment]
Hi!
You need to call `useI18n` with global scope
I’ll update vue-i18n docs.
https://github.com/intlify/vue-i18n-next/pull/1221/files

Thanks!
