### ISSUE TITLE
Could not read from file: /node_modules/dist/vue-i18n.mjs

### ISSUE THREAD

**Issue by k0mar12** [nuxt-modules/i18n#1794]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.3.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.7`
- Build Modules:    `-`

### Reproduction

[Repo](https://github.com/k0mar12/i18n-nuxt-vuetify)

### Describe the bug

While using **vuetify@3.1.1** and **@nuxtjs/i18n@8.0.0-beta.7** i got error when vuetify cant find **vue-i18n**
Modules work individually, but fail together. 

### Logs

```shell
✘ [ERROR] Could not read from file: /Users/vladposhvaniuk/Documents/develop/web/own/nuxt3/node_modules/dist/vue-i18n.mjs

    node_modules/@nuxtjs/i18n/node_modules/vue-i18n-routing/node_modules/@intlify/vue-i18n-bridge/lib/index.mjs:10:14:
      10 │ export * from 'vue-i18n'
         ╵               ~~~~~~~~~~


 ERROR  3:34:01 PM [vite] error while updating dependencies:                                                   15:34:01
Error: Build failed with 1 error:
node_modules/@nuxtjs/i18n/node_modules/vue-i18n-routing/node_modules/@intlify/vue-i18n-bridge/lib/index.mjs:10:14: ERROR: Could not read from file: /Users/vladposhvaniuk/Documents/develop/web/own/nuxt3/node_modules/dist/vue-i18n.mjs
    at failureErrorWithLog (/Users/vladposhvaniuk/Documents/develop/web/own/nuxt3/node_modules/esbuild/lib/main.js:1575:15)
    at /Users/vladposhvaniuk/Documents/develop/web/own/nuxt3/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/Users/vladposhvaniuk/Documents/develop/web/own/nuxt3/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/Users/vladposhvaniuk/Documents/develop/web/own/nuxt3/node_modules/esbuild/lib/main.js:1031:7)
    at /Users/vladposhvaniuk/Documents/develop/web/own/nuxt3/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/Users/vladposhvaniuk/Documents/develop/web/own/nuxt3/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/Users/vladposhvaniuk/Documents/develop/web/own/nuxt3/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/Users/vladposhvaniuk/Documents/develop/web/own/nuxt3/node_modules/esbuild/lib/main.js:656:7)                                                                                                             15:33:58
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
```

**Comment by zbLiuLiu** [comment]
Add`"overrides": {
    "vue-i18n": "^9.3.0-beta.16"
  }` to your `package.json`.

**Comment by k0mar12** [comment]
@zbLiuLiu Yeah, thanks. I know about this hack. But this is not working as you describe, overrides little diff:

```
{
  "dependencies": {
    "vue-i18n": "^9.3.0-beta.16",
    "vuetify": "^3.1.1"
  },
  "overrides": {
    "vuetify": {
      "vue-i18n": "$vue-i18n"
    }
  }
```

**Comment by zbLiuLiu** [comment]
@k0mar12 This is my `package.json`, I just created my project yesterday:
```
{
  ...
  "devDependencies": {
    ...
    "@nuxtjs/i18n": "^8.0.0-beta.7",
    "nuxt": "^3.0.0"
  },
  "dependencies": {
    ...
    "vue-i18n": "^9.3.0-beta.16",
    "vuetify": "^3.1.1"
  },
  "overrides": {
    "vue-i18n": "^9.3.0-beta.16"
  }
}
```
