### ISSUE TITLE
Cannot read properties of undefined (reading 'Symbol(vue-i18n-routing-gor)') - installModule with nuxt

### ISSUE THREAD

**Issue by antony-k1208** [nuxt-modules/i18n#1949]
### Environment

Nuxi 3.3.1                                                                                                                                                                                11:28:46
                                                                                                                                                                                          11:28:47
RootDir: /home/projects/github-tjkrqq                                                                                                                                                     11:28:47
Nuxt project info:                                                                                                                                                                        11:28:47

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-tjkrqq?file=package.json,src%2Fmodule.ts

### Describe the bug

When you install the Module via @nuxt/kit `installModule` helper function, you'll get the following message and the application breaks:

`[Vue warn]: injection "usehead" not found.                                                                                                                                                11:26:28
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'Symbol(vue-i18n-routing-gor)')                                                                     11:26:28
  at Module.registerGlobalOptions (./node_modules/.pnpm/vue-i18n-routing@0.12.2_vue-i18n@9.3.0-beta.17/node_modules/vue-i18n-routing/dist/vue-i18n-routing.mjs:476:26)  
  at eval (./node_modules/.pnpm/@nuxtjs+i18n-edge@8.0.0-beta.10-27993103.e65d8f2/node_modules/@nuxtjs/i18n-edge/dist/runtime/plugins/i18n.mjs:49:25)  
  at async Object.callAsync (file://./node_modules/.pnpm/unctx@2.1.2/node_modules/unctx/dist/index.mjs:72:16)  
  at async applyPlugin (./node_modules/.pnpm/nuxt@3.3.1_eslint@8.36.0/node_modules/nuxt/dist/app/nuxt.js:113:23)  
  at async Module.applyPlugins (./node_modules/.pnpm/nuxt@3.3.1_eslint@8.36.0/node_modules/nuxt/dist/app/nuxt.js:123:5)  
  at async createNuxtAppServer (./node_modules/.pnpm/nuxt@3.3.1_eslint@8.36.0/node_modules/nuxt/dist/app/entry.js:29:7)  
  at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (file://./node_modules/.pnpm/@nuxt+vite-builder@3.3.1_eslint@8.36.0+vue@3.2.47/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:42:18)                       11:21:52
  at async Object.renderToString (file://./node_modules/.pnpm/vue-bundle-renderer@1.0.2/node_modules/vue-bundle-renderer/dist/runtime.mjs:198:19)  
  at async eval (file://./playground/.nuxt/dev/index.mjs:775:21)  
  at async eval (file://./playground/.nuxt/dev/index.mjs:407:22)`

### Additional context

We have to wrap the module with our own module, since we are adding additional functionality. Our plugin is configurable and also if you don't use it, i18n shouldn't be installed in the first place, that's why we abstract the nuxt/i18n module away and install it only conditionally.

**Comment by dolbex** [comment]
Echoing that we are experiencing the same issue.

**Comment by kazupon** [comment]
I have confirmed that this issue does not occur with the latest version of nuxt edge & nuxt 3.6.5 or later.
So I will close it.
