### ISSUE TITLE
Failed nuxt prepare command

### ISSUE THREAD

**Issue by Luferov** [nuxt-modules/i18n#1976]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.8.1`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `modules`, `apollo`, `i18n`, `vite`, `build`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@nuxtjs/i18n@8.0.0-beta.10`, `@nuxtjs/tailwindcss@6.6.4`, `@nuxtjs/robots@3.0.0`, `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/apollo@5.0.0-alpha.6`, `@nuxt/devtools@0.3.1`
- Build Modules:    `-`

### Reproduction

git clone git@github.com:devind-team/partsorder.git partsorder
cd partsorder
rm package-lock.json # if exists
rm yarn.lock # if exists
rm pnpm-lock.yaml # if exists
npm i # or pnpm or yarn

### Describe the bug

npm i
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/26242554/229352839-db26b6fb-ab12-4b25-8980-3e3d2cf4826a.png">

pnpm install
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/26242554/229638760-3a830cda-6b70-4125-80e1-e2351d5a2fc9.png">

@danielroe https://github.com/nuxt/nuxt/issues/19866#issuecomment-1494145649
> But it's an issue stemming from https://github.com/nuxt-modules/i18n/blob/next/src/module.ts#L326-L328 (upstream in https://github.com/unjs/pkg-types).
> The cause is that there is no package lockfile when nuxi prepare runs. You could probably work around it by removing it from your postinstall or just including a package lockfile in your project.

### Logs

```shell
Scope: all 3 workspace projects
server                                   |  WARN  deprecated apollo-server-express@3.12.0
server                                   |  WARN  deprecated rimraf@4.1.2
server                                   |  WARN  deprecated subscriptions-transport-ws@0.11.0
server                                   |  WARN  deprecated apollo-server-types@3.8.0
server                                   |  WARN  deprecated apollo-server-core@3.12.0
server                                   |  WARN  deprecated apollo-datasource@3.3.2
server                                   |  WARN  deprecated apollo-reporting-protobuf@3.4.0
server                                   |  WARN  deprecated apollo-server-env@4.2.1
server                                   |  WARN  deprecated apollo-server-errors@3.3.1
server                                   |  WARN  deprecated apollo-server-plugin-base@3.7.2
server                                   |  WARN  deprecated uuid@3.4.0
client                                   |  WARN  deprecated @npmcli/move-file@2.0.1
client                                   |  WARN  deprecated sourcemap-codec@1.4.8
Packages: +11 -14
+++++++++++--------------
Progress: resolved 1809, reused 1788, downloaded 0, added 0, done
client postinstall$ nuxt prepare
│ Nuxi 3.3.3
│  ERROR  Cannot resolve vue-i18n on yarn! please install it on 'node_modules'
│   at tryResolve (/Users/victor/WebstormProjects/partsorder/node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.10_vue@3.2.47/node_modules/@nuxtjs/i18n/dist/module.mjs:116:9)
│   at async setupAlias (/Users/victor/WebstormProjects/partsorder/node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.10_vue@3.2.47/node_modules/@nuxtjs/i18n/dist/module.mjs:215:38)
│   at async setup (/Users/victor/WebstormProjects/partsorder/node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.10_vue@3.2.47/node_modules/@nuxtjs/i18n/dist/module.mjs:964:5)
│   at async normalizedModule (/Users/victor/WebstormProjects/partsorder/node_modules/.pnpm/@nuxt+kit@3.3.3/node_modules/@nuxt/kit/dist/index.mjs:170:17)
│   at async installModule (/Users/victor/WebstormProjects/partsorder/node_modules/.pnpm/@nuxt+kit@3.3.3/node_modules/@nuxt/kit/dist/index.mjs:452:15)
│   at async initNuxt (/Users/victor/WebstormProjects/partsorder/node_modules/.pnpm/nuxt@3.3.3_eslint@8.35.0_sass@1.58.3_typescript@5.0.3/node_modules/nuxt/dist/index.mjs:2477:7)
│   at async loadNuxt (/Users/victor/WebstormProjects/partsorder/node_modules/.pnpm/nuxt@3.3.3_eslint@8.35.0_sass@1.58.3_typescript@5.0.3/node_modules/nuxt/dist/index.mjs:2531:5)
│   at async loadNuxt (/Users/victor/WebstormProjects/partsorder/node_modules/.pnpm/@nuxt+kit@3.3.3/node_modules/@nuxt/kit/dist/index.mjs:540:19)
│   at async Object.invoke (/Users/victor/WebstormProjects/partsorder/node_modules/.pnpm/nuxi@3.3.3/node_modules/nuxi/dist/chunks/prepare.mjs:37:18)
│   at async _main (/Users/victor/WebstormProjects/partsorder/node_modules/.pnpm/nuxi@3.3.3/node_modules/nuxi/dist/cli.mjs:49:20)
└─ Failed in 706ms at /Users/victor/WebstormProjects/partsorder/client
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Luferov** [comment]
Good works with @nuxtjs/i18n@^8.0.0-beta.5.

**Comment by rahul-dutt-sharma** [comment]
this is happening on beta-11 !

**Comment by luke-z** [comment]
Also happens for me on beta 11, workaround is

- remove the package from package.json and nuxt.config.ts
- install packages
- add the package to package.json and nuxt.config.ts
- install package

**Comment by luke-z** [comment]
Still happening with rc.2
