### ISSUE TITLE
switchLocalePath not working after deploy Nuxt3

### ISSUE THREAD

**Issue by vionijannet** [nuxt-modules/i18n#1978]
Hi, I have a problem using switchLocalePath after deploy my project.

Here is my code

```
<template>
   <span @click='changeLang("en")'>EN</span> | <span @click='changeLang("id")'>ID</span>
<template>

<script lang="ts" setup>
const switchLocalePath = useSwitchLocalePath();
const { locale } = useI18n();

function changeLang(lang: string): void {
    console.log("lang", lang);
    if (locale.value !== lang) window.location.href = switchLocalePath(lang);
}
</script>
```

This code works on local, but after I deploy the project, even the function changeLang is not getting called. 
It also shows error message on console.

```
Uncaught TypeError: o.default.locale is not a function
    at entry.1b6dda79.js:34:75000
    at entry.1b6dda79.js:34:74371
    at entry.1b6dda79.js:34:74378
    at entry.1b6dda79.js:34:75020
```

I don't really know is this a bug or there is something missing on my project.
Below is the package I used in the project. 

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/i18n": "^8.0.0-beta.10",
    "@nuxtjs/tailwindcss": "^6.3.0",
    "@pinia/nuxt": "^0.4.6",
    "autoprefixer": "^10.4.13",
    "js-convert-case": "^4.2.0",
    "nuxt": "3.0.0",
    "pinia": "^2.0.30",
    "postcss": "^8.4.21",
    "sass": "^1.57.1",
    "sass-loader": "^13.2.0",
    "tailwindcss": "^3.2.4"
  },
  "dependencies": {
    "@types/crypto-js": "^4.1.1",
    "axios": "^0.21.1",
    "crypto-js": "^4.1.1",
    "rxjs": "^6.6.7",
    "sweetalert2": "^11.7.2",
    "vue-datepicker-next": "^1.0.3"
  }
}
```

I don't know if this will helped, but here is the nuxt.config.ts
```
export default defineNuxtConfig({
    modules: [
        "@nuxtjs/tailwindcss",
        "@pinia/nuxt",
        "@nuxtjs/i18n",
    ],
    i18n: {
        locales: [
            {
                code: "id",
                name: "Indonesia"
            },
            {
                code: "en",
                name: "English"
            },
        ],
        defaultLocale: "id",
        strategy: "prefix",
        vueI18n: {
            legacy: false,
            locale: "id",
            messages = {
                id: { home: "Beranda" },
                en: { home: "Home" }
            },
        }
    },
});
```

Btw I deploy on OCP using docker. This is the dockerfile.

```
# Image to use for node and nginx
ARG NODE_IMAGE=image-registry.openshift-image-registry.svc:5000/my-project/node:14.17.6

# Stage 1: Compile and Build React codebase

# Use OCP node image as the base image
FROM ${NODE_IMAGE} as build

# Set the working directory
WORKDIR /usr/local/app

# Add the source code to app
COPY ./ /usr/local/app/

# Install all the dependencies
RUN npm install

# Generate the build of the application
RUN npm run build

# ====================================

# Stage 2: Serve app with node js server

# Use OCP nginx image as the base image
FROM ${NODE_IMAGE}

# Copy the build output to replace the default nginx contents.
COPY --from=build /usr/local/app/.output ./.output

# expose port 3000
EXPOSE 3000

# Run nuxt js
CMD [ "node", ".output/server/index.mjs" ]
```

**Comment by ineshbose** [comment]
Hi, thanks for opening an issue on the repository and also thank you for including your code!

We're very swamped at the moment (other feature implementations for the module, day jobs, etc) - to help us help you faster/better, would you be able to create an accessible minimum replication (using your code) over a webcontainer please?

> 👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
> 👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

**Comment by vionijannet** [comment]
I think I found the issue, it showed after I install vue-datepicker-next library.
Thank you for the response.
