### ISSUE TITLE
[@nuxtjs/i18n]: The vueI18n option is no longer be specified with object.

### ISSUE THREAD

**Issue by hixb** [nuxt-modules/i18n#1995]
### Environment

**Nuxt Version**
^3.3.3

**Nuxt/i18n Version**
^8.0.0-beta.10

**Node Version**
v14.21.2

**Operating System**
Windows10

### Reproduction

GitHub LInk: https://github.com/hixb/my-nuxt

### Describe the bug

 ERROR  Cannot start nuxt:  [@nuxtjs/i18n]: The vueI18n option is no longer be specified with object.                                                                       14:23:07
It must be specified in the configuration file via the 'i18n.config' path.
About deprecated reason, see https://v8.i18n.nuxtjs.org/guide/migrating#change-the-route-key-rules-in-pages-option
About new configuration style, sqee https://v8.i18n.nuxtjs.org/getting-started/basic-usage#translate-with-vue-i18n

  It must be specified in the configuration file via the 'i18n.config' path.
  About deprecated reason, see https://v8.i18n.nuxtjs.org/guide/migrating#change-the-route-key-rules-in-pages-option
  About new configuration style, sqee https://v8.i18n.nuxtjs.org/getting-started/basic-usage#translate-with-vue-i18n
  at setup (/C:/my-project/my-nuxt/node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.11/node_modules/@nuxtjs/i18n/dist/module.mjs:1543:13)
  at async normalizedModule (/C:/my-project/my-nuxt/node_modules/.pnpm/@nuxt+kit@3.4.1/node_modules/@nuxt/kit/dist/index.mjs:170:17)
  at async installModule (/C:/my-project/my-nuxt/node_modules/.pnpm/@nuxt+kit@3.4.1/node_modules/@nuxt/kit/dist/index.mjs:452:95)
  at async initNuxt (/C:/my-project/my-nuxt/node_modules/.pnpm/nuxt@3.4.1_n7ukliavdvs4pkipo4bvsyofrm/node_modules/nuxt/dist/index.mjs:2616:7)
  at async load (/C:/my-project/my-nuxt/node_modules/.pnpm/nuxi@3.4.1/node_modules/nuxi/dist/chunks/dev.mjs:6824:9)
  at async Object.invoke (/C:/my-project/my-nuxt/node_modules/.pnpm/nuxi@3.4.1/node_modules/nuxi/dist/chunks/dev.mjs:6874:5)
  at async _main (/C:/my-project/my-nuxt/node_modules/.pnpm/nuxi@3.4.1/node_modules/nuxi/dist/cli.mjs:47:20)

**Comment by kazupon** [comment]
The reason why you can no longer use object is said in the error message.
Please check the docs.

thanks!
