### ISSUE TITLE
Dev preview with big translations file ~500kb breaks project

### ISSUE THREAD

**Issue by VeselyJan92** [nuxt-modules/i18n#2000]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v19.8.1`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `vite`, `components`, `server`, `target`, `head`, `loading`, `css`, `plugins`, `experimental`, `modules`, `content`, `sitemap`, `googleFonts`, `i18n`
- Runtime Modules:  `@nuxt/content@2.5.2`, `@pinia/nuxt@0.4.7`, `@nuxtjs/google-fonts@3.0.0`, `@nuxtjs/i18n@8.0.0-beta.11`, `@nuxtjs/sitemap@4.0.4`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/p/github/nuxt/starter/csb-cteu3e/draft/wizardly-silence?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A16%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A16%2C%22startLineNumber%22%3A5%7D%5D&workspace=%257B%2522activeFilepath%2522%253A%2522%252Fi18n.config.ts%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fi18n.config.ts%2522%252C%2522%252Fpackage.json%2522%252C%2522%252Fnuxt.config.ts%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clgh2m5dg00132v6jyq7zsd86%2522%253A%257B%2522key%2522%253A%2522clgh2m5dg00132v6jyq7zsd86%2522%252C%2522name%2522%253A%2522Terminal%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clgh2urmr00sn7mgt3jk05u9t%2522%252C%2522key%2522%253A%2522clgh2url001zr2v6j57tqpeu3%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%252C%2522clgh2zro702s42v6jrdoydymg%2522%253A%257B%2522key%2522%253A%2522clgh2zro702s42v6jrdoydymg%2522%252C%2522devtools%2522%253A%255B%255D%252C%2522name%2522%253A%2522New%2522%257D%252C%2522clgh300sb02vd2v6j67op0i1s%2522%253A%257B%2522key%2522%253A%2522clgh300sb02vd2v6j67op0i1s%2522%252C%2522devtools%2522%253A%255B%255D%252C%2522name%2522%253A%2522Preview%2520-%25203001%2522%257D%257D%252C%2522currentSpace%2522%253A%2522clgh2m5dg00132v6jyq7zsd86%2522%252C%2522spacesOrder%2522%253A%255B%2522clgh2m5dg00132v6jyq7zsd86%2522%252C%2522clgh2zro702s42v6jrdoydymg%2522%252C%2522clgh300sb02vd2v6j67op0i1s%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

```
import { LocaleMessage } from "@intlify/core-base"
import { I18nOptions } from "@nuxtjs/i18n"

export default defineI18nConfig( async (nuxt): Promise<I18nOptions> => ({
     messages:{
       en : await loadLocale("en"),
     },
}))

const loadLocale = async (locale: string): Promise<LocaleMessage> => {
  return new Promise(async (resolve, reject) => {

      const langFile = {
          very_long_message: 'x'.repeat(8*1024 * 500)
      }

    resolve(langFile)

  })
}
```

### Describe the bug

With resonable amount of translations ~500kb I can't run:

` yarn run dev`

### Logs

```shell
Nuxi 3.3.3
Nuxt 3.3.3 with Nitro 2.3.3

  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.0.2:3000/
  > Network:  http://[2a02:8308:308:a600:b41b:1f16:5da3:332d]:3000/

ℹ Vite client warmed up in 3688ms
[nitro] ✔ Nitro built in 877 ms
[Vue warn]: Property "$t" was accessed during render but is not defined on instance.
[nuxt] [request error] [unhandled] [431]  (431 Request Header Fields Too Large (http://localhost:3000/__nuxt_vite_node__/module/data:text/javascript;charset=utf-8,export%2520default%2520%257B%250A%2520%2520%2522en%2522%253A%2520%257B%250A%2520%2520%2522hot_info%2522%253A%2520(()%253D%253E%257Bconst%2520fn%253D(ctx)%2520%253D%253E%2520%257Bconst%2520%257B%2520normalize%253A%2520_normalize%2520%257D%2520%253D%2520ctx%253Breturn%2520_normalize(%255B%2522Interesting%2520stays%2520in%2520May%2520and%2520summer%2520is%2520starting%2520to%2520fill%2520up.%2520Don't%2520hesitate%2520with%2520your%2520vacation.%2522%255D)%257D%253Bfn.source%253D%2522Interesting%2520stays%2520in%2520May%2520and%2520summer%2520is%2520starting%2520to%2520fill%2520up.%2520Don't%2520hesitate%2520with%2520your%2520vacation.%2522%253Breturn%2520fn%253B%257D)()%252C%250A%2520%2520%2522hot_info_ok%2522%253A%2520(()%253D%253E%257Bconst%2520fn%253D(ctx)

...

 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.fetchModule (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:41:14)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:224:46)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:159:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:207:14)  
  at async evalResource (./virtual:nuxt:/home/vesely/dev/personal/web-penzion/.nuxt/i18n.internal.mjs:389:12)  
  at async Module.precompileMessages (./virtual:nuxt:/home/vesely/dev/personal/web-penzion/.nuxt/i18n.internal.mjs:434:33)  
  at async __vite_ssr_exports__.default (./�@nuxtjs/i18n/__config__:16:23)  
  at async vueI18nConfigLoader (./.nuxt/i18n.options.mjs:20:19)  
  at async Module.resolveNuxtI18nOptions (./.nuxt/i18n.options.mjs:23:19)
[Vue warn]: Property "$t" was accessed during render but is not defined on instance.
[nuxt] [request error] [unhandled] [500] _ctx.$t is not a function
  at _sfc_ssrRender (./error.vue:15:47)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:710:17)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:644:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:755:22)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:719:13)  
  at ./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:29  
  at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:865:24)  
  at async renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:907:20)  
  at async Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:4383:18)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:177:20)
```
```

**Comment by VeselyJan92** [comment]
This TODO that was probably not checked:

https://github.com/nuxt-modules/i18n/blame/dd40bfea28c829a3ace5c27696301a633f2273c2/src/runtime/internal.ts#L508

**Comment by AnyFork** [comment]
same

**Comment by PierreSchwang** [comment]
As a workaround for local development I can recommend setting Server-Side-Rendering to false in nuxt.config.ts (`ssr: false`).
The issue is in the dynamic module resolution of nuxt when running with ssr enabled - not great, but works for now.

**Comment by kazupon** [comment]
I've fixed this issue.
Please check edge channel 8.0.0-beta.11-28059008.d1499b6 version.
Thanks!

**Comment by AnyFork** [comment]
> I've fixed this issue. Please check edge channel 8.0.0-beta.11-28059008.d1499b6 version. Thanks!

I tried to avoid this problem by lazily loading translation files

**Comment by MrEraxd** [comment]
It looks like `npx nuxi generate` does not work:

```
[18:48:08]  ERROR  (node:30976) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.


 ERROR  [nuxt] [request error] [unhandled] [500] Unexpected token 'export'                                         18:48:08  
  at internalCompileFunction (node:internal/vm:73:18)
  at wrapSafe (node:internal/modules/cjs/loader:1176:20)
  at Module._compile (node:internal/modules/cjs/loader:1218:27)
  at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
  at Module.load (node:internal/modules/cjs/loader:1117:32)
  at Module._load (node:internal/modules/cjs/loader:958:12)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
  at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

  ├─ /__i18n__/prerender/ae32be2f.js (13ms) (Error: [500] ) 
```

**Comment by VeselyJan92** [comment]
Please check this commit. New doc info. 

https://github.com/nuxt-modules/i18n/commit/f12b041f2c1de04abc9646776c4eae87a9d94779

**Comment by guillaumeduhan** [comment]
Thanks @VeselyJan92 really helped me
