### ISSUE TITLE
Updating from beta.10 to beta.11 inside of a module doesn't seem to work

### ISSUE THREAD

**Issue by jpsc** [nuxt-modules/i18n#2021]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.2`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@9.6.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jpsc/beta.11.bug

### Describe the bug

Updating from beta.10 to beta.11 and the fact that the file now needs to be loaded separately doesn't seem to work when configuring it inside of a module.

### Logs

```shell
[2:18:50 PM]  ERROR  Internal server error: Failed to resolve import "/Users/jpsc/workspace/shell-nuxt-3/playground/Users/jpsc/workspace/shell-nuxt-3/src/module/i18n.config.ts?config=true" from "@nuxtjs/i18n/__config__?target=../Users/jpsc/workspace/shell-nuxt-3/src/module/i18n.config.ts&c=66edb2fd&from=/Users/jpsc/workspace/shell-nuxt-3/playground/.nuxt/i18n.options.mjs". Does the file exist?
  Plugin: vite:import-analysis
  File: @nuxtjs/i18n/__config__?target=../Users/jpsc/workspace/shell-nuxt-3/src/module/i18n.config.ts&c=66edb2fd&from=/Users/jpsc/workspace/shell-nuxt-3/playground/.nuxt/i18n.options.mjs:5:0
  3  |  import { isObject, isFunction } from '@intlify/shared'
  4  |  export default async function(context) {
  5  |    const loader = await import("/Users/jpsc/workspace/shell-nuxt-3/playground/Users/jpsc/workspace/shell-nuxt-3/src/module/i18n.config.ts?config=true").then(m => m.default || m)
     |                                ^
  6  |    const config = isFunction(loader)
  7  |      ? await loader(context)
      at formatError (file:///Users/jpsc/workspace/shell-nuxt-3/node_modules/vite/dist/node/chunks/dep-24daf00c.js:42591:46)
      at TransformContext.error (file:///Users/jpsc/workspace/shell-nuxt-3/node_modules/vite/dist/node/chunks/dep-24daf00c.js:42587:19)
      at normalizeUrl (file:///Users/jpsc/workspace/shell-nuxt-3/node_modules/vite/dist/node/chunks/dep-24daf00c.js:40498:33)                    2:18:50 PM
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///Users/jpsc/workspace/shell-nuxt-3/node_modules/vite/dist/node/chunks/dep-24daf00c.js:40641:47
      at async Promise.all (index 3)
      at async TransformContext.transform (file:///Users/jpsc/workspace/shell-nuxt-3/node_modules/vite/dist/node/chunks/dep-24daf00c.js:40567:13)
      at async file:///Users/jpsc/workspace/shell-nuxt-3/node_modules/vite-plugin-inspect/dist/index.mjs:777:23
      at async Object.transform (file:///Users/jpsc/workspace/shell-nuxt-3/node_modules/vite/dist/node/chunks/dep-24daf00c.js:42865:30)
      at async loadAndTransform (file:///Users/jpsc/workspace/shell-nuxt-3/node_modules/vite/dist/node/chunks/dep-24daf00c.js:53344:29)
```

**Comment by kazupon** [comment]
I've fixed this issue.
Please check edge channel 8.0.0-beta.11-28059008.d1499b6 version.
Thanks!

**Comment by jpsc** [comment]
Thanks for the fix @kazupon .

I've tried to update to the latest edge and it doesn't seem to work yet.
This is how we can get the latest edge right?

```json
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",
```

I'm also fine waiting for the beta.12 if you have other priorities 👍
Keep up the great work!

**Comment by kazupon** [comment]
> I've tried to update to the latest edge and it doesn't seem to work yet.

Could you give us your errors 🙏 ?

**Comment by jpsc** [comment]
The error is the same as before. I've just updated the reproduction repo with the edge dependency.

**Comment by kazupon** [comment]
I've confirmed your reproduction repository.

You need to define the vue-i18n (`createI18n`) options only.
Please see the docs:
https://v8.i18n.nuxtjs.org/getting-started/basic-usage

**Comment by jpsc** [comment]
Thanks. I know understand my mistake 👍
It's fixed.
