### ISSUE TITLE
431 Request Header Fields Too Large

### ISSUE THREAD

**Issue by mudoo** [nuxt-modules/i18n#2023]
### Environment

- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/sandbox/nervous-fast-vrx75y

### Describe the bug

can not start nuxt service when config `vueI18n: './i18n.config.ts'`

### Logs

```shell
[10:08:03 AM] [Vue warn]: Property "$t" was accessed during render but is not defined on instance.
[10:08:03 AM] [nuxt] [request error] [unhandled] [431]  (431 Request Header Fields Too Large (http://localhost:3000/__nuxt_vite_node__/module/data:text/javascript;charset=utf-8,export%2520default%2520%257B%250A%2520%2520%2522en%2522%253A%2520%257B%250A%2520%2520%2522hello%2522%253A%2520(()%253D%253E%257Bconst%2520fn%253D(ctx)%2520%253D%253E%2520%257Bconst%2520%257B%2520normalize%253A%2520_normalize%2520%257D%2520%253D%2520ctx%253Breturn%2520_normalize(%255B%2522hello%2522%255D)%257D%253Bfn.source%253D%2522hello%2522%253Breturn%2520fn%253B%257D)()     [......lot more]
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async Object.fetchModule (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:41:14)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:238:46)
[10:08:03 AM] [Vue warn]: Property "$t" was accessed during render but is not defined on instance.
[nuxt] [request error] [unhandled] [500] _ctx.$t is not a function 10:08:03 AM
  at _sfc_ssrRender (./error.vue:11:47)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:710:17)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:644:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:755:22)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:719:13)  
  at ./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:29  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:865:24)  
  at async renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:907:20)  
  at async Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:755:18)
```

**Comment by ineshbose** [comment]
Please check #2008 and #2000!
