### ISSUE TITLE
Failed to load locale loading: Unexpected token 'export'

### ISSUE THREAD

**Issue by bitbytebit1** [nuxt-modules/i18n#2051]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      css, plugins, buildModules, modules, i18n
- Runtime Modules:  nuxt-purgecss@2.0.0, @nuxtjs/i18n@8.0.0-beta.11-28059008.d1499b6
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-fxzxma?file=package.json

### Describe the bug

When building my project I get the error below
  

### Logs

```shell
ℹ Prerendering 2 routes                                                                                                                                                   nitro 12:36:03 AM

 ERROR  (node:181237) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.                                                        12:36:04 AM
(Use node --trace-warnings ... to show where the warning was created)


 ERROR  [nuxt] [request error] [unhandled] [500] Unexpected token 'export'                                                                                                      12:36:04 AM
  at compileFunction (<anonymous>)  
  at Object.compileFunction (node:vm:352:18)  
  at wrapSafe (node:internal/modules/cjs/loader:1033:15)  
  at Module._compile (node:internal/modules/cjs/loader:1069:27)  
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)  
  at Module.load (node:internal/modules/cjs/loader:981:32)  
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)  
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)  
  at async ./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:836:18  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1247:19)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async generateRoute (./node_modules/nitropack/dist/shared/nitro.6e79de60.mjs:95:17)  
  at async prerender (./node_modules/nitropack/dist/shared/nitro.6e79de60.mjs:153:22)  
  at async ./node_modules/nuxt/dist/index.mjs:2289:7  
  at async build (./node_modules/nuxt/dist/index.mjs:3176:5)  
  at async Object.invoke (./node_modules/nuxi/dist/chunks/build.mjs:55:5)  
  at async _main (./node_modules/nuxi/dist/cli.mjs:48:20)
 ERROR  (node:181237) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.                                                        12:36:04 AM


 ERROR  @nuxtjs/i18n Failed locale loading: Unexpected token 'export'                                                                                                           12:36:04 AM

  ├─ /__i18n__/prerender/83755bf2.js (828ms) (Error: [500] )                                                                                                              nitro 12:36:04 AM

 ERROR  (node:181237) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.                                                        12:36:04 AM


 ERROR  [nuxt] [request error] [unhandled] [500] Unexpected token 'export'                                                                                                      12:36:04 AM
  at compileFunction (<anonymous>)  
  at Object.compileFunction (node:vm:352:18)  
  at wrapSafe (node:internal/modules/cjs/loader:1033:15)  
  at Module._compile (node:internal/modules/cjs/loader:1069:27)  
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)  
  at Module.load (node:internal/modules/cjs/loader:981:32)  
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)  
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)  
  at async ./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:836:18  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1247:19)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async generateRoute (./node_modules/nitropack/dist/shared/nitro.6e79de60.mjs:95:17)  
  at async prerender (./node_modules/nitropack/dist/shared/nitro.6e79de60.mjs:153:22)  
  at async ./node_modules/nuxt/dist/index.mjs:2289:7  
  at async build (./node_modules/nuxt/dist/index.mjs:3176:5)  
  at async Object.invoke (./node_modules/nuxi/dist/chunks/build.mjs:55:5)  
  at async _main (./node_modules/nuxi/dist/cli.mjs:48:20)


 ERROR  @nuxtjs/i18n Failed locale loading: Unexpected token 'export'                                                                                                           12:36:04 AM

  ├─ /__i18n__/prerender/18705b4e.js (57ms) (Error: [500] )                                                                                                               nitro 12:36:04 AM
```

**Comment by cuebit** [comment]
Can confirm this occurs in recent edge releases. Falling back to `8.0.0-beta.11-28025896.b896eaa` seems stable.

**Comment by kazupon** [comment]
As added to docs in PR #2052, `"type": "module"` must be set in package.json after `8.0.0-beta.11` version

**Comment by bitbytebit1** [comment]
I'm weirdly experiencing this same error (but only on my server!) after updating my package.json, building and deploying
