### ISSUE TITLE
An error occurred when using the '@nuxtjs/i18n' plugin for packaging in nuxt3

### ISSUE THREAD

**Issue by AnyFork** [nuxt-modules/i18n#2071]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.17.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      runtimeConfig, app, modules, svgo, robots, i18n, components, css, vite, imports
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12, @nuxtjs/robots@3.0.0, nuxt-svgo@2.0.0, nuxt-windicss@2.6.1, @vueuse/nuxt@10.1.0
- Build Modules:    -
------------------------------

### Reproduction

none

### Describe the bug

The following error occurred when using the latest version for packaging
```

[22:45:48]  ERROR  [nuxt] [request error] [unhandled] [500] Cannot find module 'G:\Web_Project\YunDao\YiHui\m_yihui\dist\server\_nuxt\i18n.config-0ae2e280.js' imported from G:\Web_Project\YunDao\YiHui\m_yihui\.nuxt\prerender\chunks\nitro-prerenderer.mjs
  at new NodeError (node:internal/errors:387:5)
  at finalizeResolution (node:internal/modules/esm/resolve:429:11)
  at moduleResolve (node:internal/modules/esm/resolve:1006:10)
  at defaultResolve (node:internal/modules/esm/resolve:1214:11)
  at nextResolve (node:internal/modules/esm/loader:165:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
  at ESMLoader.import (node:internal/modules/esm/loader:528:22)
  at importModuleDynamically (node:internal/modules/esm/translators:110:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
  at /G:/Web_Project/YunDao/YiHui/m_yihui/.nuxt/prerender/chunks/nitro-prerenderer.mjs:24923:18
  at async Object.handler (/G:/Web_Project/YunDao/YiHui/m_yihui/node_modules/.pnpm/registry.npmmirror.com+h3@1.6.4/node_modules/h3/dist/index.mjs:1247:19)
  at async toNodeHandle (/G:/Web_Project/YunDao/YiHui/m_yihui/node_modules/.pnpm/registry.npmmirror.com+h3@1.6.4/node_modules/h3/dist/index.mjs:1322:7)
  at async ufetch (/G:/Web_Project/YunDao/YiHui/m_yihui/node_modules/.pnpm/registry.npmmirror.com+unenv@1.4.1/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async generateRoute (/G:/Web_Project/YunDao/YiHui/m_yihui/node_modules/.pnpm/registry.npmmirror.com+nitropack@2.3.3/node_modules/nitropack/dist/shared/nitro.96034a6e.mjs:4190:17)
  at async prerender (/G:/Web_Project/YunDao/YiHui/m_yihui/node_modules/.pnpm/registry.npmmirror.com+nitropack@2.3.3/node_modules/nitropack/dist/shared/nitro.96034a6e.mjs:4248:22)
  at async /G:/Web_Project/YunDao/YiHui/m_yihui/node_modules/.pnpm/registry.npmmirror.com+nuxt@3.4.2_@types+node@18.0.0/node_modules/nuxt/dist/index.mjs:2226:7
  at async build (/G:/Web_Project/YunDao/YiHui/m_yihui/node_modules/.pnpm/registry.npmmirror.com+nuxt@3.4.2_@types+node@18.0.0/node_modules/nuxt/dist/index.mjs:3110:5)
  at async Object.invoke (/G:/Web_Project/YunDao/YiHui/m_yihui/node_modules/.pnpm/registry.npmmirror.com+nuxi@3.4.2/node_modules/nuxi/dist/chunks/build.mjs:55:5)
  at async _main (/G:/Web_Project/YunDao/YiHui/m_yihui/node_modules/.pnpm/registry.npmmirror.com+nuxi@3.4.2/node_modules/nuxi/dist/cli.mjs:48:20)
```
The path here seems incorrect, nuxt path is `. nuxtt`
![image](https://github.com/nuxt-modules/i18n/assets/49142023/9a229f4c-9d26-4474-9778-f0f45d950e3b)

**Comment by ineshbose** [comment]
Hi, thanks for opening an issue. A minimum reproduction of the issue would really help understand and point the exact issue, because right now I'm unable to tell your configuration for Nuxt and i18n.

You can use https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz as starter.

**Comment by AnyFork** [comment]
> Hi, thanks for opening an issue. A minimum reproduction of the issue would really help understand and point the exact issue, because right now I'm unable to tell your configuration for Nuxt and i18n.
> 
> You can use https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz as starter.

It may be a dependency issue, I deleted `node_modules` directory has been reinstalled and the dependencies are ready for normal packaging
