### ISSUE TITLE
Do not support relative paths

### ISSUE THREAD

**Issue by 1923998238** [nuxt-modules/i18n#2114]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.17
- Builder:          vite
- User Config:      app, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-kpw7eu?file=nuxt.config.ts

### Describe the bug

我的英文不是很好 我是用翻译软件来写这些内容， 在nuxt.config.ts配置中  baseURL为process.env.NODE_ENV === 'production' ? './' : '/',时、也就是相对路径的，运行npm run generate 就会报错 Invalid URL (./__i18n__/precompile)

My English is not very good. I use translation software to write these contents. In the nuxt.config.ts configuration, the baseurl is process.env.node_env === 'Production'? './':/' Just relative paths, running NPM Run Generate will report an error invalid url (./__i18n__/precompile))

https://stackblitz.com/edit/github-kpw7eu?file=nuxt.config.ts

### Additional context

![image](https://github.com/nuxt-modules/i18n/assets/64238420/dbc125e2-54e2-47c6-810e-a3fa7caae5c4)

### Logs

```shell
❯ npm run generate
$ nuxt generate
Nuxi 3.5.1                                                                                                        23:33:18
Nuxt 3.5.1 with Nitro 2.4.1                                                                                       23:33:18

[23:33:22]  WARN  Using experimental payload extraction for full-static output. You can opt-out by setting experimental.payloadExtraction to false.


[@nuxtjs/i18n 23:33:23]  WARN  i18n:extend-messages is deprecated. That hook will be removed feature at the time of the v8 official release.
If you're using it, please use i18n:registerModule instead.

ℹ Building client...                                                                                              23:33:28
ℹ vite v4.3.9 building for production...                                                                          23:33:28
ℹ ✓ 123 modules transformed.                                                                                      23:33:33
ℹ .nuxt/dist/client/i18n-meta.json                       0.08 kB │ gzip:  0.09 kB                                 23:33:37
ℹ .nuxt/dist/client/manifest.json                        2.71 kB │ gzip:  0.50 kB                                 23:33:37
ℹ .nuxt/dist/client/_nuxt/error-500.aa16ed4d.css         1.95 kB │ gzip:  0.74 kB                                 23:33:37
ℹ .nuxt/dist/client/_nuxt/error-404.23f2309d.css         3.63 kB │ gzip:  1.12 kB                                 23:33:37
ℹ .nuxt/dist/client/_nuxt/i18n.dbd056e4.js               0.31 kB │ gzip:  0.25 kB                                 23:33:37
ℹ .nuxt/dist/client/_nuxt/i18n.options.5f857b57.js       0.39 kB │ gzip:  0.28 kB                                 23:33:37
ℹ .nuxt/dist/client/_nuxt/error-component.2af1f68d.js    1.07 kB │ gzip:  0.60 kB                                 23:33:37
ℹ .nuxt/dist/client/_nuxt/error-500.931e2945.js          1.88 kB │ gzip:  0.99 kB                                 23:33:37
ℹ .nuxt/dist/client/_nuxt/error-404.820276bd.js          6.50 kB │ gzip:  2.88 kB                                 23:33:37
ℹ .nuxt/dist/client/_nuxt/entry.0463bc6d.js            157.88 kB │ gzip: 57.28 kB                                 23:33:37
ℹ ✓ built in 8.86s                                                                                                23:33:37
✔ Client built in 8906ms                                                                                          23:33:37
ℹ Building server...                                                                                              23:33:37
ℹ vite v4.3.9 building SSR bundle for production...                                                               23:33:37
ℹ ✓ 71 modules transformed.                                                                                       23:33:40
rendering chunks (11)...Sourcemap is likely to be incorrect: a plugin (nuxtjs:i18n-resource-dynamic) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
ℹ .nuxt/dist/server/i18n-meta.json                              0.08 kB                                           23:33:41
ℹ .nuxt/dist/server/_nuxt/error-404-styles.a5c3f351.mjs         0.08 kB                                           23:33:41
ℹ .nuxt/dist/server/_nuxt/error-500-styles.6b5b5ff2.mjs         0.08 kB                                           23:33:41
ℹ .nuxt/dist/server/styles.mjs                                  0.35 kB                                           23:33:41
ℹ .nuxt/dist/server/_nuxt/index-e12b288f.js                     0.22 kB │ map:   5.28 kB                          23:33:41
ℹ .nuxt/dist/server/_nuxt/i18n-96367a5c.js                      0.51 kB │ map:   0.12 kB                          23:33:41
ℹ .nuxt/dist/server/_nuxt/island-renderer-c7f12f68.js           1.25 kB │ map:   1.41 kB                          23:33:41
ℹ .nuxt/dist/server/_nuxt/i18n.options-8843531b.js              1.46 kB │ map:   0.15 kB                          23:33:41
ℹ .nuxt/dist/server/_nuxt/error-component-74ec86f1.js           2.04 kB │ map:   2.71 kB                          23:33:41
ℹ .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-0a86f27a.js    2.17 kB │ map:   0.12 kB                          23:33:41
ℹ .nuxt/dist/server/_nuxt/error-dev-styles-1.mjs-90bc7cbc.js    2.46 kB │ map:   0.12 kB                          23:33:41
ℹ .nuxt/dist/server/_nuxt/error-500-01d90197.js                 3.25 kB │ map:   3.79 kB                          23:33:41
ℹ .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-6ef6e240.js    3.86 kB │ map:   0.12 kB                          23:33:41
ℹ .nuxt/dist/server/_nuxt/error-404-25e89dfb.js                 9.87 kB │ map:  18.88 kB                          23:33:41
ℹ .nuxt/dist/server/server.mjs                                138.11 kB │ map: 335.50 kB                          23:33:41
ℹ ✓ built in 3.80s                                                                                                23:33:41
✔ Server built in 3837ms                                                                                          23:33:41
✔ Generated public .output/public                                                                           nitro 23:33:41
ℹ Initializing prerenderer                                                                                  nitro 23:33:41
ℹ Prerendering 4 initial routes with crawler                                                                nitro 23:33:44

 ERROR  [nuxt] [request error] [unhandled] [500] Invalid URL (./__i18n__/precompile)                              23:33:45
  at async Module.precompileConfig (file://./.nuxt/prerender/chunks/app/server.mjs:3343:5)  
  at async i18n_options (file://./.nuxt/prerender/chunks/app/_nuxt/i18n.options-8843531b.mjs:51:23)  
  at async vueI18nConfigLoader (file://./.nuxt/prerender/chunks/app/server.mjs:3007:81)  
  at async resolveNuxtI18nOptions (file://./.nuxt/prerender/chunks/app/server.mjs:3009:19)  
  at async Object.eval [as setup] (file://./.nuxt/prerender/chunks/app/server.mjs:3636:173)  
  at async Object.callAsync (file://./node_modules/unctx/dist/index.mjs:91:16)  
  at async applyPlugin (file://./.nuxt/prerender/chunks/app/server.mjs:151:33)  
  at async applyPlugins (file://./.nuxt/prerender/chunks/app/server.mjs:167:7)  
  at async createNuxtAppServer (file://./.nuxt/prerender/chunks/app/server.mjs:4046:7)  
  at async Object.renderToString (file://./node_modules/vue-bundle-renderer/dist/runtime.mjs:202:19)

  ├─ / (415ms) (Error: [500] )                                                                              nitro 23:33:45

 ERROR  [nuxt] [request error] [unhandled] [500] Invalid URL (./__i18n__/precompile)                              23:33:45
  at async Module.precompileConfig (file://./.nuxt/prerender/chunks/app/server.mjs:3343:5)  
  at async i18n_options (file://./.nuxt/prerender/chunks/app/_nuxt/i18n.options-8843531b.mjs:51:23)  
  at async vueI18nConfigLoader (file://./.nuxt/prerender/chunks/app/server.mjs:3007:81)  
  at async resolveNuxtI18nOptions (file://./.nuxt/prerender/chunks/app/server.mjs:3009:19)  
  at async Object.eval [as setup] (file://./.nuxt/prerender/chunks/app/server.mjs:3636:173)  
  at async Object.callAsync (file://./node_modules/unctx/dist/index.mjs:91:16)  
  at async applyPlugin (file://./.nuxt/prerender/chunks/app/server.mjs:151:33)  
  at async applyPlugins (file://./.nuxt/prerender/chunks/app/server.mjs:167:7)  
  at async createNuxtAppServer (file://./.nuxt/prerender/chunks/app/server.mjs:4046:7)  
  at async Object.renderToString (file://./node_modules/vue-bundle-renderer/dist/runtime.mjs:202:19)
```

**Comment by dargmuesli** [comment]
Does **Nuxt's** baseURL even support relative paths?
Also, why do you think that this issue is related to nuxt-i18n, not Nuxt itself?

**Comment by 1923998238** [comment]
> **Nuxt 的**baseURL 甚至支持相对路径吗？ 另外，为什么你认为这个问题与 nuxt-i18n 有关，而不是 Nuxt 本身？

Yes, baseURL in nuxt3 supports relative paths. If the website needs to be deployed to a non-root directory, then the baseURL needs to be configured as a relative path.

I'm not exactly sure where the problem lies, but I do know that this issue occurred after enabling the @nuxtjs/i18n module. Prior to enabling @nuxtjs/i18n, npm run generate configured as a relative path can run successfully.

**Comment by 1923998238** [comment]
> **Nuxt 的**baseURL 甚至支持相对路径吗？ 另外，为什么你认为这个问题与 nuxt-i18n 有关，而不是 Nuxt 本身？

Yes, baseURL in nuxt3 supports relative paths. If the website needs to be deployed to a non-root directory, then the baseURL needs to be configured as a relative path.

I'm not exactly sure where the problem lies, but I do know that this issue occurred after enabling the @nuxtjs/i18n module. Prior to enabling @nuxtjs/i18n, npm run generate configured as a relative path can run successfully.

![image](https://github.com/nuxt-modules/i18n/assets/64238420/d7baffa2-a0e2-49f3-bb24-3a0112012712)
