### ISSUE TITLE
[nuxtjs:i18n-resource-dynamic] Plugin error - Unable to get file name for unknown file "7dc266f9".

### ISSUE THREAD

**Issue by ajaythakkar** [nuxt-modules/i18n#2126]
### Environment

production

### Reproduction

npm run build

### Describe the bug

[nuxtjs:i18n-resource-dynamic] Plugin error - Unable to get file name for unknown file "7dc266f9".

 ERROR  Plugin error - Unable to get file name for unknown file "7dc266f9".                                                                 7:52:53 PM

  at error (/D:/Wamp/www/client/horse-management/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
  at Object.FileEmitter.getFileName (/D:/Wamp/www/client/horse-management/node_modules/rollup/dist/es/shared/node-entry.js:24128:24)
  at /D:/Wamp/www/client/horse-management/node_modules/@nuxtjs/i18n/dist/module.mjs:1216:50
  at Array.reduce (<anonymous>)
  at Object.generateBundle (/D:/Wamp/www/client/horse-management/node_modules/@nuxtjs/i18n/dist/module.mjs:1215:44)
  at /D:/Wamp/www/client/horse-management/node_modules/rollup/dist/es/shared/node-entry.js:24551:40
  at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by EtienneBruines** [comment]
See https://github.com/nuxt-modules/i18n/issues/2029

**Comment by ineshbose** [comment]
Please provide a reproduction of the issue over Stackblitz using https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz so we can investigate it better. If the issue linked by Etienne is not related to yours, please let me know and I'll reopen the issue. 🙂

**Comment by ajaythakkar** [comment]
This is work for me : 
npm install @nuxtjs/i18n@8.0.0-beta.11
