### ISSUE TITLE
fail nuxt preview, because there is no file unde output/public/__i18n__/

### ISSUE THREAD

**Issue by henkelhiedl-dev-team** [nuxt-modules/i18n#2170]
### Environment

- nuxt: 3.5.2
- @nuxtjs/i18n: 8.0.0-beta.12

### Reproduction

https://github.com/yoshito-maeoka/nuxt-i18n-prerender-problem

### Describe the bug

  with  nuxt dev  works.                                                                                              
```                                                                                                                      
    ❯ yarn dev                                                                                                        
    yarn run v1.22.18                                                                                                 
    $ nuxt dev                                                                                                        
      > Local:    http://localhost:3000/                                                                              
            :                                                                                                         
            :                                                                                                         
    ✔ Nuxt Devtools is enabled v0.5.5 ℹ Vite client warmed up in 710ms                                                
    ✔ Nitro built in 379 ms                                                                                           
    ✔ Vite server hmr 21 files in 822.595ms                                                                           
                                                                                                                      
  Image: en → https://github.com/yoshito-maeoka/nuxt-i18n-prerender-problem/blob/main/assets/img/en.png               
  Image: ja → https://github.com/yoshito-maeoka/nuxt-i18n-prerender-problem/blob/main/assets/img/ja.png               
 ```                                                                                                                     
  but with  nuxt preview  does not work.                                                                              
  ```                                                                                                                    
    ❯ yarn preview                                                                                                    
    yarn run v1.22.18                                                                                                 
    $ nuxt preview                                                                                                    
    Nuxi 3.5.3                                                                                                        
                :
                :                                                                                                                      
    Listening http://[::]:3000                                                                                        
    @nuxtjs/i18n Cannot find module '/Users/an-user/work/nuxt-i18n-prerender-                                         
  problem/.output/public/__i18n__/prerender/e525609c.js' imported from /Users/an-user/work/nuxt-i18n-prerender-       
  problem/.output/server/chunks/app/_nuxt/i18n.options-810bdec2.mjs                                                   
    [nuxt] [request error] [unhandled] [500] Cannot read properties of null (reading 'e525609c')                      
      at ./server/chunks/nitro/node-server.mjs:813:26                                                                 
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                   
      at async Object.handler (./server/node_modules/h3/dist/index.mjs:1255:19)                                       
      at async Server.toNodeHandle (./server/node_modules/h3/dist/index.mjs:1330:7)                                   
                                                                                                                      
  Image: ng → https://github.com/yoshito-maeoka/nuxt-i18n-prerender-problem/blob/main/assets/img/ng.png               
```

under .output/public does not exist __i18n__ directory
```
❯ ls .output/public 
_nuxt		favicon.ico
```

**Comment by AlexRoehm** [comment]
May be related to how the config is prerendered into an ESM. See related:

https://github.com/nuxt/nuxt/issues/21051

This is currently a problem for me in production. I would greatly appreciate a fix

**Comment by kaboume** [comment]
same issue.
Translate works on local mode (npm run dev) but after deploy, no translation and the same error message in logs 

` Cannot find module '/var/www/XXX/.output/public/__i18n__/prerender/a30fcf66.js' imported from /var/www/XXX/.output/server/chunks/app/_nuxt/i18n.options-1fb8b9a5.mjs`
