### ISSUE TITLE
Import of defineI18nConfig fails

### ISSUE THREAD

**Issue by highhi** [nuxt-modules/i18n#2182]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.5.0
- Package Manager:  pnpm@8.6.3
- Builder:          vite
- User Config:      srcDir, runtimeConfig, modules, app, css, i18n, imports
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.0, @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -

### Reproduction

https://github.com/highhi/nuxt-i18n-bug-reproduction

### Describe the bug

I have auto import disabled in my project.

```
export default defineNuxtConfig({
  modules: ["@nuxtjs/i18n"],
  imports: {
    autoImport: false,
  },
});
```

So I tried to explicitly import defineI18nConfig.

```
import { defineI18nConfig } from "#i18n";

export default defineI18nConfig(() => ({
  ...
}));
```

But, this results in an error. 

```
defineI18nConfig is not defined

at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ViteNodeRunner.directRequest (./node_modules/.pnpm/vite-node@0.32.2_@types+node@18.0.0/node_modules/vite-node/dist/client.mjs:334:5)
at async ViteNodeRunner.cachedRequest (./node_modules/.pnpm/vite-node@0.32.2_@types+node@18.0.0/node_modules/vite-node/dist/client.mjs:190:14)
at async ViteNodeRunner.dependencyRequest (./node_modules/.pnpm/vite-node@0.32.2_@types+node@18.0.0/node_modules/vite-node/dist/client.mjs:224:12)
at async __vite_ssr_exports__.default (./@nuxtjs/i18n/__config__:8:18)
at async vueI18nConfigLoader (./.nuxt/i18n.options.mjs:20:19)
at async Module.resolveNuxtI18nOptions (./.nuxt/i18n.options.mjs:23:19)
at async ./node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.12_vue@3.3.4/node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n.mjs:22:154
```

I have tried the following import and get the same error.

```
- import { defineI18nConfig } from "@nuxtjs/i18n/dist/runtime/composables.mjs";
- import { defineI18nConfig } from "#imports";
```

**Comment by kazupon** [comment]
Thank you for your reporting!

This is an issue because the docs don't mention the import id `#i18n` provided by the nuxt i18n module when `autoImport: false` is used.

We will put it in the docs.

**Comment by bissolli** [comment]
It didn't work for me even in the edge version!
I don't use auto imports in my project, is there any way to by pass the problem? Any way I can import it?

**Comment by bounoable** [comment]
I just ran into the same issue while developing a Nuxt module. Auto-imports are disabled by default in the module starter playground and I'm getting the same error when importing `defineI18nConfig` from #i18n.

**Comment by bounoable** [comment]
Solved it by just exporting the configuration without using `defineI18nConfig`:

```ts
// i18n.config.ts
export default {
  legacy: false,
  locale: 'en',
  messages: {},
}

```

**Comment by craigvantonder** [comment]
Having the same problem with `autoImport: false` in both:

-  `@nuxtjs/i18n": "^8.0.0-rc.3`
- `"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"`

https://github.com/nuxt-modules/i18n/issues/2182#issuecomment-1617529847 indicates that #i81n is not available with `autoImport: false`, okay so then manual import should be possible:

    // i18n.config.ts
    import { defineI18nConfig } from "@nuxtjs/i18n/dist/runtime/composables";
    export default defineI18nConfig(() => ({
    ....

But it fails with an error:

    ERROR  Internal server error: Missing "./dist/runtime/composables" specifier in "@nuxtjs/i18n" package
      Plugin: vite:import-analysis
      File: /path/to/i18n.config.ts?hash=bdcce7a0&config=1
          at e (file:///path/to/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:16647:25)
          at n (file:///path/to/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:16647:627)
          at o (file:///path/to/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:16647:1297)
          at resolveExportsOrImports (file:///path/to/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23405:20)
          at resolveDeepImport (file:///path/to/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23424:31)
          at tryNodeResolve (file:///path/to/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
          at Context.resolveId (file:///path/to/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async Object.resolveId (file:///path/to/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:32)
          at async TransformContext.resolve (file:///path/to/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42575:23) (x2)

https://github.com/nuxt-modules/i18n/issues/2182#issuecomment-1671714248 is working but it does not seem like that is the solution to the issue.

Seems to be the same issue #2012 which mentioned https://github.com/nuxt-modules/i18n/issues/2012#issuecomment-1515926291 that it was solved and caused by malformed import of defineI18nConfig.

What is the correct way to import `defineI18nConfig` when `autoImport: false`?
