### ISSUE TITLE
How to configure I18n when nuxt3's builder using webpack?

### ISSUE THREAD

**Issue by chaosLich** [nuxt-modules/i18n#2314]
First time using i18n and nuxt3, and here is my `nuxt.config.ts`:
```typescript
export default defineNuxtConfig({
    builder: 'webpack',
    build: {
        transpile: [
            'vue-demi',
        ]
    },
    modules: [
        '@nuxtjs/i18n',
    ],
    i18n: {
        vueI18n: './i18n.config',
    },
})
```
And I've encounter this error: "Cannot redefine property: locales"
```
500
Cannot redefine property: locales

at Function.defineProperty ()
at extendVueI18n (/D:/code/testI18n/.nuxt/dist/server/server.mjs:3759:14)
at pluginOptions.__vueI18nExtend (/D:/code/testI18n/.nuxt/dist/server/server.mjs:3644:9)
at Proxy.beforeCreate (/D:/code/testI18n/.nuxt/dist/server/server.mjs:7538:14)
at callWithErrorHandling (D:\code\testI18n\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:156:32)
at callWithAsyncErrorHandling (D:\code\testI18n\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:164:17)
at callWithAsyncErrorHandling (D:\code\testI18n\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:174:17)
at callHook (D:\code\testI18n\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:3501:3)
at applyOptions (D:\code\testI18n\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:3279:5)
at finishComponentSetup (D:\code\testI18n\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7295:5)
```

It seems that this variable "locales" has been defined twice...Is there anyway to fix this?

**Comment by YarikSWT** [comment]
Same situation

**Comment by BobbieGoede** [comment]
Could you provide a minimal reproduction of this issue? I am unable to replicate this issue with the latest RC version, [here is a starter project](https://stackblitz.com/fork/github/BobbieGoede/nuxt-i18n-starter/tree/v8) you can use.

**Comment by chaosLich** [comment]
> Could you provide a minimal reproduction of this issue? I am unable to replicate this issue with the latest RC version, [here is a starter project](https://stackblitz.com/fork/github/BobbieGoede/nuxt-i18n-starter/tree/v8) you can use.

So I have tried to replicate this issue with  `@nuxtjs/i18n@8.0.0-rc.2`, and it did works. However, I didn't replicated it when using   `@nuxtjs/i18n@8.0.0-rc.4`. It seems like it have been fixed during the version update, maybe?

**Comment by BobbieGoede** [comment]
> It seems like it have been fixed during the version update, maybe?
In that case I'll be closing this issue! If you run into this issue again with the latest version let me know, then I will reopen it 😄
