### ISSUE TITLE
Cannot assign to read only property '0' of string 'en'

### ISSUE THREAD

**Issue by marr** [nuxt-modules/i18n#2375]
### Environment

- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.7.1
- Builder:          -
- User Config:      srcDir, modules, i18n
- Runtime Modules:  nuxt-vitest@0.10.4, @nuxtjs/i18n@8.0.0-rc.4-28231445.30514f2
- Build Modules:    -

### Reproduction

I have a layer project that uses @nuxtjs/i18n. The layer's nuxt.config defines an `i18n` prop, as does the .playground. When I try to browse the playground, the error occurs:

> Cannot assign to read only property '0' of string 'en' at mergeVueI18nConfigs (./.playground/.nuxt/i18n.options.mjs:53:15)

The following repository contains the reproduction of the issue https://github.com/marr/nuxt-i18n-rc4-layer

### Describe the bug

There appears to be a regression with merging layers configuration. When I start the app, there is no error but when browsing the page there is a major error.

### Logs

```shell
Cannot assign to read only property '0' of string 'en'

at mergeVueI18nConfigs (./.playground/.nuxt/i18n.options.mjs:53:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Module.resolveNuxtI18nOptions (./.playground/.nuxt/i18n.options.mjs:63:3)
at async setup (./node_modules/.pnpm/@nuxtjs+i18n-edge@8.0.0-rc.4-28231445.30514f2_vue-router@4.2.4_vue@3.3.4/node_modules/@nuxtjs/i18n-edge/dist/runtime/plugins/i18n.mjs:27:156)
at async Object.callAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)
at async applyPlugin (./node_modules/.pnpm/nuxt@3.7.1_eslint@8.48.0_typescript@4.9.5/node_modules/nuxt/dist/app/nuxt.js:114:25)
at async Module.applyPlugins (./node_modules/.pnpm/nuxt@3.7.1_eslint@8.48.0_typescript@4.9.5/node_modules/nuxt/dist/app/nuxt.js:134:7)
at async createNuxtAppServer (./node_modules/.pnpm/nuxt@3.7.1_eslint@8.48.0_typescript@4.9.5/node_modules/nuxt/dist/app/entry.js:28:7)
at async default (./node_modules/.pnpm/@nuxt+vite-builder@3.7.1_eslint@8.48.0_typescript@4.9.5_vue@3.3.4/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:32:18)
```

**Comment by BobbieGoede** [comment]
Thank you for reporting! I have a PR lined up to fix this, which should merge and be deployed to the edge channel shortly.

**Comment by marr** [comment]
Great. Thank you!
