### ISSUE TITLE
Issue with Nuxt 3 Layers and Nuxt i18n with remote layer

### ISSUE THREAD

**Issue by SGDS-SyL** [nuxt-modules/i18n#2491]
Running into the same issue as discussion, Layer works locally but when changed to Github repo. It failed with this:

`Failed to resolve import "/lang/en.json" from ".nuxt\i18n.options.mjs"`
I've checked and the file do exist.

### Discussed in https://github.com/nuxt-modules/i18n/discussions/2388

<div type='discussions-op-text'>

<sup>Originally posted by **ionutfrent** September  8, 2023</sup>
### Issue Description
**Package Name/Repository:** Nuxt 3 with Layers

**Nuxt i18n Version:** "@nuxtjs/i18n": "v8.0.0-rc.4"

### Issue Details
I am currently working with Nuxt 3 Layers for my project. When I extend Layers from local repositories, everything works perfect. However, when I try to extend Layers from a GitHub repository link, I encounter an issue with the Nuxt i18n package. The specific error message I'm getting is:

`ERROR  No lockfile found from /***/node_modules/base-app`

_**It's important to note that I have the latest version of "@nuxtjs/i18n" (v8.0.0-rc.4) installed in all Layers.**_

### Steps to Reproduce
To reproduce this issue, follow these steps:

- Create a Nuxt 3 project as a base Layer.

- Use Nuxt i18n in the base Layer.

- Push the project to a GitHub repository.

- Create a Nuxt 3 project which extends the base Layer from the GitHub repository link.

- Install the dependencies.

_**The base-app layer is added as a dependency in package.json as follows:**_
`"dependencies": {
    "base-app": "git+ssh://github_pat_***@github.com:***/base-app.git"
  }`

### Expected Behavior
I expected the project to run without errors when extending Layers from a GitHub repository while using the latest version of Nuxt i18n.

### Actual Behavior
Instead, I encountered the "No lockfile found" error as described above.

### Additional Notes
I'd like to highlight that the described issue appears to be introduced in the latest versions of the library. To provide some context, I experimented with an alpha version of the library, and I couldn't reproduce the issue. This suggests that there might be a regression or compatibility issue in the most recent releases of the library, specifically affecting projects using Nuxt 3 Layers in conjunction with Nuxt i18n.

cc/ @kazupon 
I would appreciate any assistance or insights from the community or individuals experienced with Nuxt 3 Layers and Nuxt i18n.</div>

**Comment by skoenfaelt** [comment]
Thank you for opening an issue. 

Just to inform as written in the discussion:
`"@nuxtjs/i18n": "8.0.0-beta.4"` solves the installation error (every newer version breaks) but with that version all translations in the layer need to move to the application.

**Comment by BobbieGoede** [comment]
I would like to look into this issue but I will need a minimal reproduction to debug the exact issue. 😅

[Nuxt `3.8.0`](https://github.com/nuxt/nuxt/releases/tag/v3.8.0) has layer improvements which may tackle the underlying issue here.

**Comment by skoenfaelt** [comment]
# Reproduction Steps
1. Checkout https://github.com/derHodrig/nuxt-i18n-reproduction
2. navigate to `i18n-app`
3. run `npm install`

> Install should fail


- i18n-app is the app and has the dependency `"@skoenfeld/i18n-layer": "0.0.2"`
- i18n-layer is the package [@skoenfeld/i18n-layer](https://www.npmjs.com/package/@skoenfeld/i18n-layer) and has the `"@nuxtjs/i18n": "^8.0.0-rc.5"` dependency
- @skoenfeld/i18n-layer is the published package


Note: Both, Layer and App do not have any configuration in their nuxt.config.ts, because the issue is in the installation of the layer. You should observe this error:

```
npm ERR!  ERROR  No lockfile found from ...\i18n-reproduction\i18n-app\node_modules\@skoenfeld\i18n-layer
npm ERR!
npm ERR!   at resolveLockfile (.../i18n-reproduction/i18n-app/node_modules/pkg-types/dist/index.mjs:122:9)
npm ERR!   at async getPackageManagerType (.../i18n-reproduction/i18n-app/node_modules/@nuxtjs/i18n/dist/module.mjs:108:26)
```

> its my first reproduction, feel free to improve me via critics ^^

**Comment by BobbieGoede** [comment]
@derHodrig 
I believe the issue you're experiencing is because the layer runs `nuxt prepare` because of the npm `postinstall` script, but lockfiles are not published in npm packages. Can you try removing the `postinstall` script and check if it works again? And of course I recommend installing the edge release channel as it includes most recent bug fixes!

>its my first reproduction, feel free to improve me via critics ^^

It's a good reproduction! As it is an npm package it is a bit hard to make changes and test, but that's something inherent to this specific issue 😅

**Comment by skoenfaelt** [comment]
@BobbieGoede did not think that this problem is that simple solved.

@SGDS-SyL could you please rename your `postinstall` script in your layer>package.json and install the new published layer?
https://github.com/derHodrig/nuxt-i18n-reproduction/commit/4c88663f56c81028919cd83580be86a9fdbfce4e#diff-b68b7af82dbabeceff18a29ef8697de0c088349cd1b2a4f0a872ec92095c7802

In my case, in the reproduction, the issue was solved.

Downturn is, after your install deps in the layer, you have to manually use the `nuxt prepare .playground`

**Comment by BobbieGoede** [comment]
>In my case, in the reproduction, the issue was solved.

Glad to hear the issue was solved for you! 

>Downturn is, after your install deps in the layer, you have to manually use the nuxt prepare .playground

Hmm, have you tried updating the module to the latest edge release and seeing if the error is still thrown when keeping the `postinstall` script?

```
npm ERR!   at async getPackageManagerType (.../i18n-reproduction/i18n-app/node_modules/@nuxtjs/i18n/dist/module.mjs:108:26)
```
I believe the code that is throwing this error has been removed and is not present in the edge release.

**Comment by BobbieGoede** [comment]
Closing due to inactivity of the original issue creator, the discussion that came after may have resolved the underlying issue.
