### ISSUE TITLE
SyntaxError: Need to install with `app.use` function

### ISSUE THREAD

**Issue by leecho** [nuxt-modules/i18n#2540]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.20.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
- "@nuxtjs/i18n": "8.0.0-rc.5",

### Reproduction

null

### Describe the bug

**nuxt.config.ts**
```
import { getEnvConfig } from './nuxt/env'
const envConfig = getEnvConfig()
export default defineNuxtConfig({
    css: [
        'element-plus/theme-chalk/dark/css-vars.css',
        '@/assets/styles/index.scss'
    ],
    modules: [
        '@pinia/nuxt',
        '@nuxtjs/tailwindcss',
        '@nuxtjs/i18n',
        '@nuxtjs/color-mode'
    ],
    app: {
        baseURL: envConfig.baseUrl
    },
    runtimeConfig: {
        public: {
            ...envConfig
        }
    },
    ssr: !!envConfig.ssr,
    i18n: {
        vueI18n: './i18n.config.ts'
    }
})

```
**i18n.config.ts**
```
export default defineI18nConfig(() => ({
    globalInjection: true,
    strategy: 'prefix',
    langDir: 'locales',
    locales: [
        {
            code: 'en',
            iso: 'en-US',
            file: 'en.ts'
        },
        {
            code: 'zh',
            iso: 'zh-CN',
            file: 'zh.ts'
        }
    ],
    useCookie: true,
    defaultLocale: 'zh',
    detectBrowserLanguage: {
        useCookie: true,
        cookieKey: 'i18n_redirected',
        redirectOn: 'root'
    }
}))

```
**language.vue**
```

<template>
    <div>
        <nuxt-link
            v-for="locale in availableLocales"
            :key="locale.code"
            :to="switchLocalePath(locale.code)"
            >{{ locale.name }}
        </nuxt-link>
    </div>
</template>
<script setup lang="ts">
const { locale, locales } = useI18n()
const switchLocalePath = useSwitchLocalePath()

const availableLocales = computed(() => {
    return locales.value.filter((i) => i.code !== locale.value)
})
</script>

```

### Logs

```shell
runtime-core.esm-bundler.js:561  SyntaxError: Need to install with `app.use` function (at message-compiler.mjs:77:19)
    at createCompileError (message-compiler.mjs:77:19)
    at createI18nError (vue-i18n.mjs?v=f3adf6ba:101:12)
    at useI18n (vue-i18n.mjs?v=f3adf6ba:2299:15)
    at setup (language.vue?t=1699331923050:10:33)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7204:29)
    at setupComponent (runtime-core.esm-bundler.js:7159:11)
    at mountComponent (runtime-core.esm-bundler.js:5508:13)
    at processComponent (runtime-core.esm-bundler.js:5483:17)
    at patch (runtime-core.esm-bundler.js:5085:21)
```

**Comment by kazupon** [comment]
close due to in-activity.
if you are having still issue, please you would open as new issue.
thank you!
