### ISSUE TITLE
 Cannot start nuxt:  Cannot read properties of undefined (reading 'options') 

### ISSUE THREAD

**Issue by amirsafaricg** [nuxt-modules/i18n#2544]
### Environment

I installed i18n on my nuxt3 project that has pinia and tailwind css and color mode installed and nothing more, when I add i18n to my nuxt.config.ts what happens is that gives this error : 
` Cannot start nuxt:  Cannot read properties of undefined (reading 'options') ` 

this is my nuxt.config.ts file : 
`// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: false },
  css: ['~/assets/css/main.css'],
  modules:['@pinia/nuxt','@nuxtjs/color-mode', '@nuxtjs/i18n'],
  i18n: {
    vueI18n: './i18n.config.ts' // if you are using custom path, default 
  },
  colorMode: {
    classSuffix: '',
    preference: 'light',
    fallback: 'light',
  },
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
})
`

### Reproduction

just follow basic instructions of adding tailwind css since in @nuxtjs/tailwind the dark mode class doesnt work :
https://tailwindcss.com/docs/guides/nuxtjs
pinia : 
https://pinia.vuejs.org/ssr/nuxt.html
and color-mode
https://color-mode.nuxtjs.org/
and i18n : 
https://nuxt.com/modules/i18n

### Describe the bug

Doesnt let the dev server to start for this error : 
` Cannot start nuxt:  Cannot read properties of undefined (reading 'options') `

### Logs

```shell
ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'options')                                                                                                                                                          1:32:12 PM  

  at _default (D:/Projects/Production/Personal/website 2/portfolio-website/portfolio-website/node_modules/@nuxtjs/i18n/src/index.js:15:92)
  at installModule (/D:/Projects/Production/Personal/website%202/portfolio-website/portfolio-website/node_modules/@nuxt/kit/dist/index.mjs:2439:101)
  at async initNuxt (/D:/Projects/Production/Personal/website%202/portfolio-website/portfolio-website/node_modules/nuxt/dist/index.mjs:3696:7)
  at async NuxtDevServer._load (/D:/Projects/Production/Personal/website%202/portfolio-website/portfolio-website/node_modules/nuxi/dist/chunks/dev2.mjs:255:5)
  at async NuxtDevServer.load (/D:/Projects/Production/Personal/website%202/portfolio-website/portfolio-website/node_modules/nuxi/dist/chunks/dev2.mjs:187:7)
  at async NuxtDevServer.init (/D:/Projects/Production/Personal/website%202/portfolio-website/portfolio-website/node_modules/nuxi/dist/chunks/dev2.mjs:182:5)
  at async Object.run (/D:/Projects/Production/Personal/website%202/portfolio-website/portfolio-website/node_modules/nuxi/dist/chunks/dev-child.mjs:103:5)
  at async runCommand$1 (/D:/Projects/Production/Personal/website%202/portfolio-website/portfolio-website/node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1647:7)
  at async runCommand$1 (/D:/Projects/Production/Personal/website%202/portfolio-website/portfolio-website/node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1638:11)
  at async runMain$1 (/D:/Projects/Production/Personal/website%202/portfolio-website/portfolio-website/node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1770:7)
```

**Comment by remvn** [comment]
I think you installed older version by using `npm i -D @nuxtjs/i18n` (v7 for nuxt2)
it should be `npm i -D @nuxtjs/i18n@next` as they mentioned in the [docs](https://i18n.nuxtjs.org/getting-started/setup)

**Comment by AdeoRemiDoolaeghe** [comment]
I've encoutered the same issue on a Windows machine. Using WSL to perform the `nuxt prepare` is a potential workaround. I don't know if the issue could come back when I'll have to install another dependency in my project.

**Comment by amirsafaricg** [comment]
Thanks everyone for the kind support and guidance 
the version of I18n I had to use to fix this issue was different, I fixed it fortunately, Thanks everyone. ❤️

**Comment by BobbieGoede** [comment]
@AdeoRemiDoolaeghe if you're still experiencing this issue, could provide a reproduction?

Glad to hear this issue has been resolved for you @amirsafaricg!
