### ISSUE TITLE
After latest updates, when installing the npm packages it issues Could not resolve module "@intlify/vue-router-bridge/lib/index.mjs"

### ISSUE THREAD

**Issue by vinixhenri** [nuxt-modules/i18n#2565]
### Environment

- Operating System: Darwin
- Node Version:     v18.12.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      ssr, vite, app, css, modules, buildModules, runtimeConfig, imports, pinia, i18n, swiper, pwa, vuetify, robots, sitemap, gtm, recaptcha, amp
- Runtime Modules:  @pinia/nuxt@0.4.11, nuxt-swiper@1.2.2, nuxt-simple-sitemap@1.0.11, nuxt-simple-robots@1.0.9, nuxt-graphql-client@0.2.31, @nuxtjs/i18n@8.0.0-rc.5-28339831.ee5fc28, ()
- Build Modules:    -

### Reproduction

nuxt 3 + i18n-next

### Describe the bug

After latest updates on i18n-edge pkg, it started issuing an error (`Could not resolve module "@intlify/vue-router-bridge/lib/index.mjs"`)

This happens when installing the npm pkgs with (`npm i`)

### Logs

```shell
ERROR  Could not resolve module "@intlify/vue-router-bridge/lib/index.mjs"       9:42:20 AM

  at setupAlias (node_modules/@nuxtjs/i18n/dist/module.mjs:105:13)
  at async setup (node_modules/@nuxtjs/i18n/dist/module.mjs:1228:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2141:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2439:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3702:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3789:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2584:19)
  at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:56:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7)
```

**Comment by vinixhenri** [comment]
I can confirm this issue is not happening when using the 8.0.0-rc.5-28284892.1fc1f02 version. I may be something that changed in between 8.0.0-rc.5-28296269.d5d5540 and 8.0.0-rc.5-28284892.1fc1f02.

**Comment by BobbieGoede** [comment]
Thank you for reporting! 

This is the same issue as https://github.com/nuxt-modules/i18n/issues/2556 so I will be closing this so we track this in a single issue. Please refer to the workaround described there while we figure out a fix 😄
