### ISSUE TITLE
Error: Could not resolve module "@intlify/vue-router-bridge/lib/index.mjs" 

### ISSUE THREAD

**Issue by erikuit** [nuxt-modules/i18n#2583]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      app, sourcemap, vite, components, modules, i18n, runtimeConfig, googleFonts, build, css
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.6, @nuxtjs/google-fonts@3.1.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ihvwd9-nbwn5u

### Describe the bug

After the release of RC6 I'm getting this error in my projects, with `npm run dev`, `npm run build` or even on a fresh install (see reproduction):

```
 ERROR  Could not resolve module "@intlify/vue-router-bridge/lib/index.mjs"                                     2:47:20 PM

  at setupAlias (node_modules/@nuxtjs/i18n/dist/module.mjs:120:13)
  at async setup (node_modules/@nuxtjs/i18n/dist/module.mjs:1243:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2224:17)
  at async Module.installModule (node_modules/@nuxt/kit/dist/index.mjs:2522:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3719:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3806:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2667:19)
  at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:71:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1678:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1669:11) 
  ```

**Comment by s00d** [comment]
same problem

**Comment by BobbieGoede** [comment]
Let's track this issue here https://github.com/nuxt-modules/i18n/issues/2556

**Comment by agracia-foticos** [comment]
Same problem
