### ISSUE TITLE
Could not resolve module "@intlify/vue-i18n-bridge/lib/index.mjs"   when i upgrade to i18n 8.0.0 RC 9

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt-modules/i18n#2611]
### Environment

- Operating System: `Linux`
- Node Version:     `v20.5.1`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@9.8.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Could not resolve module "@intlify/vue-i18n-bridge/lib/index.mjs"   when i upgrade to i18n 8.0.0 RC 9

`Could not resolve module "@intlify/vue-i18n-bridge/lib/index.mjs"                                                                                11:53:51

  at setupAlias (node_modules/@nuxtjs/i18n/dist/module.mjs:117:13)
  at async setup (node_modules/@nuxtjs/i18n/dist/module.mjs:1397:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2141:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2439:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3702:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3789:5)
  at async Module.loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2584:19)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:73:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11) `

### Describe the bug

Could not resolve module "@intlify/vue-i18n-bridge/lib/index.mjs"   when i upgrade to i18n 8.0.0 RC 9

### Additional context

Could not resolve module "@intlify/vue-i18n-bridge/lib/index.mjs"   when i upgrade to i18n 8.0.0 RC 9

**Comment by BobbieGoede** [comment]
Thanks for reporting, can you try removing `node_modules` and `package-lock.json` (or other lockfiles) and installing dependencies again to see if that fixes this issue? If that doesn't work, I will need a minimal reproduction to debug the issue 🙏

**Comment by agracia-foticos** [comment]
> Thanks for reporting, can you try removing `node_modules` and `package-lock.json` (or other lockfiles) and installing dependencies again to see if that fixes this issue? If that doesn't work, I will need a minimal reproduction to debug the issue 🙏

Works!!! We close the issue
