### ISSUE TITLE
Cannot destructure property 'routesNameSeparator' of '__vite_ssr_import_3__.useRuntimeConfig(...).public.i18n' as it is undefined.

### ISSUE THREAD

**Issue by wrufeger** [nuxt-modules/i18n#2890]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.6.2
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.2.0
- Build Modules:    -

### Reproduction

just install latest nuxt with nuxt/i18n

### Describe the bug

After including @nuxtjs/i18n in modules section of nuxt.config.ts I get the 500 error. Even tried to add routesNameSeparator config manually. It's working with @nuxt/i18n 8.1.1

### Logs

```shell
500
Cannot destructure property 'routesNameSeparator' of '__vite_ssr_import_3__.useRuntimeConfig(...).public.i18n' as it is undefined.

at setup (D:\dev\rufeger\enshrouded-nuxt\node_modules\@nuxtjs\i18n\dist\runtime\plugins\i18n.mjs:38:55)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async setup (D:\dev\rufeger\enshrouded-nuxt\virtual:nuxt:D:\dev\rufeger\enshrouded-nuxt\.nuxt\plugins\server.mjs:36:116)
at async Object.callAsync (/D:/dev/rufeger/enshrouded-nuxt/node_modules/unctx/dist/index.mjs:72:16)
at async applyPlugin (D:\dev\rufeger\enshrouded-nuxt\node_modules\nuxt\dist\app\nuxt.js:116:25)
at async executePlugin (D:\dev\rufeger\enshrouded-nuxt\node_modules\nuxt\dist\app\nuxt.js:153:9)
at async Module.applyPlugins (D:\dev\rufeger\enshrouded-nuxt\node_modules\nuxt\dist\app\nuxt.js:161:5)
at async createNuxtAppServer (D:\dev\rufeger\enshrouded-nuxt\node_modules\nuxt\dist\app\entry.js:26:7)
at async default (/D:/dev/rufeger/enshrouded-nuxt/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:33:18)
```

**Comment by wrufeger** [comment]
trying to reproduce the error for several hours I managed to find it. Providing reproduction via stackblitz won't work, as it depends on an malformed variable in .env, which I had fixed already locally:

    NUXT_PUBLIC=https://localhost:8000

Above config variable makes no sense, but works with 8.1.11 and fails in 8.2.0 with error message provided.

**Comment by BobbieGoede** [comment]
I don't quite understand what you're saying 😅, was this issue caused by your local setup? If that's the case can this issue be closed?

**Comment by kazupon** [comment]
Closing due to inactivity. 
Please open a new issue with a reference to this one if you can follow up with more information.

Thanks!
