### ISSUE TITLE
Cannot read properties of undefined (reading 'messages')

### ISSUE THREAD

**Issue by alexcroox** [nuxt-modules/i18n#3010]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, experimental, ssr, typescript, srcDir, runtimeConfig, extends, modules, sourcemap, ui, postcss, tailwindcss, vite, nitro, components, css, imports, i18n
- Runtime Modules:  @nuxt/test-utils/module@3.13.1, @pinia/nuxt@0.5.1, @nuxt/ui@2.17.0, @nuxtjs/i18n@8.3.1, @nuxt/fonts@0.7.1, @vueuse/nuxt@10.11.0, @nuxt/eslint@0.3.13, nuxt-eslint-auto-explicit-import@0.0.2, @nuxt/image@1.7.0, @nuxtjs/fontaine@0.4.3
- Build Modules:    -

### Reproduction

Passing an H3 event from an API eventHandler to a function in the server/utils directory causes this error:

`Cannot read properties of undefined (reading 'messages')`

### Describe the bug

My function where the error originates:

<img width="495" alt="image" src="https://github.com/nuxt-modules/i18n/assets/1065835/01ad0896-f913-403c-8050-59e902dd9f1f">

Looking at the stack trace at the bottom I think I've manage to figure out why it's erroring with this.

Firstly the localeDector is called here with 1 param (event)

<img width="727" alt="image" src="https://github.com/nuxt-modules/i18n/assets/1065835/c527e9ac-f553-4a6e-994a-77e5aa7b9a8c">

This seems to be calling this localeDetector function which requires the `i18nContext` context as it's second param.

<img width="795" alt="image" src="https://github.com/nuxt-modules/i18n/assets/1065835/762631eb-f4b5-4e14-a441-f5ba1a1bd9d7">

Which is why this line fails:

`await loadAndSetLocaleMessages(locale, localeLoaders, i18nContext.messages);`

 because i18nContext is undefined.

```
 ERROR  Cannot read properties of undefined (reading 'messages')

  at localeDetector (.nuxt/dev/index.mjs:3233:73)
  at useTranslation (node_modules/@intlify/h3/dist/index.mjs:38:39)
  at generateAndSaveTokens (.nuxt/dev/index.mjs:2717:19)
  at Object.handler (.nuxt/dev/index.mjs:6889:47)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async node_modules/h3/dist/index.mjs:1962:19
  at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
  at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (node_modules/h3/dist/index.mjs:2249:7)
 ```

**Comment by alexcroox** [comment]
it's this line here, should I be adding the issue on the intlify/h3 repo instead? 

https://github.com/intlify/h3/blob/main/src/index.ts#L355

That line is calling the line in this repo that expects the second param:

https://github.com/nuxt-modules/i18n/blob/3c3277ef172209ae1d4ce23d4b5427a476d95c76/src/runtime/server/plugin.ts#L36-L39

**Comment by BobbieGoede** [comment]
You could open an issue on the other repository but we will need a (minimal) reproduction of your issue to determine whether this is caused by configuration or a bug.

**Comment by BobbieGoede** [comment]
Closing due to inactivity and lack of minimal reproduction.

**Comment by temitopeadesoji** [comment]
Hi @alexcroox, were you able to resolve this issue, i am experiencing similar behaviour intermittently.

**Comment by alexcroox** [comment]
Unfortunately not. It happens consistently on my login endpoint the very first time I submit after a page reload. After that first usage it doesn’t happen again. Very confused

**Comment by BobbieGoede** [comment]
If you could create a reproduction I can reopen this and take a look at it 🙏

**Comment by alexcroox** [comment]
@temitopeadesoji I found a workaround, set `lazy: false` in nuxt.config and the error will not occur:

```
export default defineNuxtConfig({
  i18n: {
    lazy: false,
  }
})
```

This is because the `loadAndSetLocaleMessgaes()` function that tries to use an undefined `i18nContext` is never called if you don't use lazy. 

![Image](https://github.com/user-attachments/assets/a8505a19-d5f3-4c33-97ed-930171b5596d)

Not ideal from a performance point of view, but it will get rid of the fatal error for now.

@BobbieGoede I'll try get a reproduction together, but the issue is around i18nContext being undefined at times.

**Comment by alexcroox** [comment]
I tried to reproduce but failed to, still trying to work out what's the flow my full app uses that's causing issues.

https://stackblitz.com/edit/github-z5l3te?file=nuxt.config.ts,layers%2Fauth%2Fserver%2Fapi%2Ftest.get.ts,server%2Futils%2Ftest-util.ts,app%2Fcomponents%2FTest.vue
