### ISSUE TITLE
In server function: Cannot destructure property 'fallbackFormat' of 'context' as it is undefined.

### ISSUE THREAD

**Issue by phillipmohr** [nuxt-modules/i18n#3057]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.2.0`
- Nuxt Version:     `3.12.2`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.3.0`
- Builder:          `-`
- User Config:      `ssr`, `build`, `$production`, `$development`, `modules`, `translation-manager`, `nitro`, `supabase`, `pinia`, `runtimeConfig`, `i18n`, `css`, `postcss`, `svgo`, `routeRules`, `imports`
- Runtime Modules:  `@nuxtjs/supabase@1.2.2`, `@formkit/nuxt@1.6.5`, `@nuxtjs/tailwindcss@6.12.0`, `@nuxtjs/i18n@8.3.1`, `@pinia/nuxt@0.5.1`, `nuxt-svgo@3.7.0`, `lodash@4.17.21`, `@vueuse/nuxt@10.11.0`, `nuxt-cron@1.5.1`, `nuxt-translation-manager@1.1.0`, `nuxt-nodemailer@1.1.2`
- Build Modules:    `-`

### Reproduction

I'll provide a reproduction later but maybe someone can already help.

### Describe the bug

I'm using nuxt i18n in my server route. I followed this documentation: https://i18n.nuxtjs.org/docs/guide/server-side-translations 

This is my code: 
```ts
async function handleLeadCreation(event: H3Event<EventHandlerRequest>) {
  const t = await useTranslation(event)
  const subject = t('email.new_lead.subject', { campaign_name: 'Summer Campaign' })
})
```
  
The error I'm getting: 
```
ERROR  [nitro] [unhandledRejection] Cannot destructure property 'fallbackFormat' of 'context' as it is undefined.

  at translate (node_modules/.pnpm/@intlify+core-base@9.13.1/node_modules/@intlify/core-base/dist/core-base.mjs:1095:13)
  at translate$1 (node_modules/.pnpm/@intlify+h3@0.5.0/node_modules/@intlify/h3/dist/index.mjs:41:28)
  at handleLeadCreation (server/api/facebook/webhooks/index.post.ts:129:1)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Additional context

I should note that I'm also using nuxt-translation-manager. Not sure if this has something to do with the issue.

**Comment by phillipmohr** [comment]
Sorry, the issue was on my end! I called the `handleLeadCreation` function from another function and forgot to call with an `await`. This is why the error occurred!
