### ISSUE TITLE
Vue app aliases are not allowed in server runtime

### ISSUE THREAD

**Issue by kaaax0815** [nuxt-modules/i18n#3111]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.15.0`
- Nuxt Version:     `3.13.0`
- CLI Version:      `3.13.1`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.10.0`
- Builder:          `-`
- User Config:      `future`, `compatibilityDate`, `devtools`, `modules`, `colorMode`, `i18n`, `nitro`
- Runtime Modules:  `@nuxtjs/i18n@8.5.1`, `@nuxtjs/tailwindcss@6.12.1`, `@pinia/nuxt@0.5.4`, `@eschricht/nuxt-color-mode@1.1.5`, `radix-vue/nuxt`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-e2l8kn

### Describe the bug

See logs

### Logs

```shell
ERROR  Vue app aliases are not allowed in server runtime. [importing #build/i18n.options.mjs from node_modules/.pnpm/@nuxtjs+i18n@8.5.1_magicast@0.3.5_rollup@4.21.2_vue@3.4.38_typescript@5.5.4_/node_modules/@nuxtjs/i18n/dist/runtime/composables/index.js]                          10:09:25 AM


 ERROR  Error: Could not load /Users/berndstorath/Documents/wg-easy/src/i18n.config.ts?hash=bffaebcb&config=1 (imported by .nuxt/i18n.options.mjs): ENOENT: no such file or directory, open '/Users/berndstorath/Documents/wg-easy/src/i18n.config.ts?hash=bffaebcb&config=1'      nitro 10:09:27 AM


undefined


 ERROR  Could not load /Users/berndstorath/Documents/wg-easy/src/i18n.config.ts?hash=bffaebcb&config=1 (imported by .nuxt/i18n.options.mjs): ENOENT: no such file or directory, open '/Users/berndstorath/Documents/wg-easy/src/i18n.config.ts?hash=bffaebcb&config=1'                   10:09:27 AM

  at async open (node:internal/fs/promises:639:25)
  at async readFile (node:internal/fs/promises:1249:14)
  at async node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:19003:24
  at async Queue.work (node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:20028:32) 



 ERROR  Could not load /Users/berndstorath/Documents/wg-easy/src/i18n.config.ts?hash=bffaebcb&config=1 (imported by .nuxt/i18n.options.mjs): ENOENT: no such file or directory, open '/Users/berndstorath/Documents/wg-easy/src/i18n.config.ts?hash=bffaebcb&config=1'
```

When updating all packages

```shell
[nitro 10:37:39 AM]  ERROR  RollupError: [plugin impound] Vue app aliases are not allowed in server runtime. [importing #build/i18n.options.mjs from node_modules/.pnpm/@nuxtjs+i18n@8.5.3_magicast@0.3.5_rollup@4.22.0_vue@3.5.6_typescript@5.6.2_/node_modules/@nuxtjs/i18n/dist/runtime/composables/index.js]


undefined


 ERROR  [plugin impound] Vue app aliases are not allowed in server runtime. [importing #build/i18n.options.mjs from node_modules/.pnpm/@nuxtjs+i18n@8.5.3_magicast@0.3.5_rollup@4.22.0_vue@3.5.6_typescript@5.6.2_/node_modules/@nuxtjs/i18n/dist/runtime/composables/index.js]          10:37:39 AM

  at getRollupError (node_modules/.pnpm/rollup@4.22.0/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
  at error (node_modules/.pnpm/rollup@4.22.0/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
  at Object.error (node_modules/.pnpm/rollup@4.22.0/node_modules/rollup/dist/es/shared/node-entry.js:19743:20)
  at Object.resolveId (node_modules/.pnpm/impound@0.1.0_rollup@4.22.0/node_modules/impound/dist/index.js:29:11)
  at node_modules/.pnpm/rollup@4.22.0/node_modules/rollup/dist/es/shared/node-entry.js:19928:40
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.22.0/node_modules/rollup/dist/es/shared/node-entry.js:19828:28)
  at async resolveId (node_modules/.pnpm/rollup@4.22.0/node_modules/rollup/dist/es/shared/node-entry.js:18519:26)
  at async ModuleLoader.resolveId (node_modules/.pnpm/rollup@4.22.0/node_modules/rollup/dist/es/shared/node-entry.js:18922:15)
  at async Object.resolveId (node_modules/.pnpm/@rollup+plugin-commonjs@25.0.8_rollup@4.22.0/node_modules/@rollup/plugin-commonjs/dist/es/index.js:588:10) 



 ERROR  [plugin impound] Vue app aliases are not allowed in server runtime. [importing #build/i18n.options.mjs from node_modules/.pnpm/@nuxtjs+i18n@8.5.3_magicast@0.3.5_rollup@4.22.0_vue@3.5.6_typescript@5.6.2_/node_modules/@nuxtjs/i18n/dist/runtime/composables/index.js] 
```

**Comment by BobbieGoede** [comment]
This is expected behavior, the server/nitro context is different from the nuxt context and cannot access the same composables and functionalities.
