### ISSUE TITLE
JSON Import Issue for messages in Vue i18n after migration

### ISSUE THREAD

**Issue by JonathanXDR** [nuxt-modules/i18n#3264]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.11.0`
- Nuxt Version:     `3.14.1592`
- CLI Version:      `3.16.0`
- Nitro Version:    `2.10.4`
- Package Manager:  `bun@1.1.38`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `@nuxt/scripts@0.9.5`, `@nuxt/eslint@0.7.3`, `@nuxt/image@1.8.1`, `@nuxt/icon@1.10.1`, `@nuxt/fonts@0.10.3`, `@nuxtjs/color-mode@3.5.2`, `@nuxtjs/i18n@9.1.1`, `@nuxtjs/seo@2.0.2`, `@nuxtjs/tailwindcss@6.12.2`, `@vueuse/nuxt@12.0.0`, `nuxt-security@2.1.5`
- Build Modules:    `-`

### Reproduction

https://github.com/JonathanXDR/Application-Website-Frontend/blob/af785e2488bd306eb8914a93b8f6fa6808940f2d

### Describe the bug

After migrating to the new Nuxt i18n directory structure, importing JSON files in i18n.config.ts does not work as expected. Instead of returning the expected localized messages, Vue I18n returns an Abstract Syntax Tree (AST). This behavior suggests that Vue I18n is not properly processing the JSON files and treats them as raw data instead of localized message objects.

### Additional context

- [i18n.config.ts](https://github.com/JonathanXDR/Application-Website-Frontend/blob/af785e2488bd306eb8914a93b8f6fa6808940f2d/i18n/i18n.config.ts)
- [nuxt.config.ts](https://github.com/JonathanXDR/Application-Website-Frontend/blob/af785e2488bd306eb8914a93b8f6fa6808940f2d/nuxt.config.ts#L195-L237)

### Logs

```shell
jonathan@MacBook-Pro-von-Jonathan Application-Website-Frontend % nr dev
$ nuxt dev --dotenv .env.local
Nuxt 3.14.1592 with Nitro 2.10.4                                                                                                                                               22:43:52
                                                                                                                                                                               22:43:52
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                                                                                          nuxt:tailwindcss 22:43:54
  ➜ DevTools: press Shift + Option + D in the browser (v1.6.4)                                                                                                                 22:43:55

ℹ Nuxt Icon server bundle mode is set to local                                                                                                                                22:43:55
✔ Nuxt Icon discovered local-installed 7 collections: carbon, fa6-brands, fa6-solid, ion, logos, ri, tabler                                                                   22:43:56
ℹ Running with compatibility version 4                                                                                                                                        22:43:56
ℹ Tailwind Viewer: http://localhost:3000/_tailwind/                                                                                                          nuxt:tailwindcss 22:43:56
✔ Vite client built in 113ms                                                                                                                                                  22:43:58
✔ Vite server built in 657ms                                                                                                                                                  22:43:58

 ERROR  [uncaughtException] Cannot read properties of undefined (reading 'target')                                                                                             22:43:59

  at createVueLanguagePlugin2 (node_modules/@vue/language-core/lib/languagePlugin.js:63:53)
  at Object.createVueLanguagePlugin (node_modules/@vue/language-core/lib/languagePlugin.js:58:12)
  at exports.getLanguagePlugins (node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/languagePlugins.cjs:40:33)
  at Object.apply (node_modules/@volar/typescript/lib/node/proxyCreateProgram.js:50:33)
  at getBuilderCreationParameters (node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/typescript-vue-tsc/lib/typescript.js:129293:18)
  at createSemanticDiagnosticsBuilderProgram (node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/typescript-vue-tsc/lib/typescript.js:129948:5)
  at createNewProgram (node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/typescript-vue-tsc/lib/typescript.js:132010:22)
  at synchronizeProgram (node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/typescript-vue-tsc/lib/typescript.js:131984:7)
  at Object.createWatchProgram (node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/typescript-vue-tsc/lib/typescript.js:131890:3)
  at Object.configureServer (node_modules/vite-plugin-checker/src/checkers/vueTsc/main.ts:143:13)

✔ Nuxt Nitro server built in 2592 ms                                                                                                                                    nitro 22:44:03
ℹ Vite client warmed up in 0ms                                                                                                                                                22:44:03
ℹ Vite server warmed up in 1249ms                                                                                                                                             22:44:05

 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol name= { type: 0,
  start: 0,
  end: 12,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 13, offset: 12 },
     source: 'sun.max.fill' },
  body:
   { type: 2,
     start: 0,
     end: 12,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'sun.max.fill' } } class="icon icon-large" > 
  at <SegmentNav items= [ { id: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 6, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } } ] gap="5px" component-size="xsmall"  ... > 
  at <NavBar> 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>


 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol name= { type: 0,
  start: 0,
  end: 9,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 10, offset: 9 },
     source: 'moon.fill' },
  body:
   { type: 2,
     start: 0,
     end: 9,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'moon.fill' } } class="icon icon-large" > 
  at <SegmentNav items= [ { id: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 6, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } } ] gap="5px" component-size="xsmall"  ... > 
  at <NavBar> 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>


 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol name= { type: 0,
  start: 0,
  end: 22,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 23, offset: 22 },
     source: 'circle.lefthalf.filled' },
  body:
   { type: 2,
     start: 0,
     end: 22,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'circle.lefthalf.filled' } } class="icon icon-large" > 
  at <SegmentNav items= [ { id: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 6, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } } ] gap="5px" component-size="xsmall"  ... > 
  at <NavBar> 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>


 WARN  [Icon] failed to load icon fa6-[object Object]:[object Object]


 WARN  [Icon] failed to load icon fa6-[object Object]:[object Object]


 WARN  [Icon] failed to load icon fa6-[object Object]:[object Object]


 WARN  [Icon] failed to load icon fa6-[object Object]:[object Object]


 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol key=2 loading=false name= { type: 0,
  start: 0,
  end: 13,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 14, offset: 13 },
     source: 'chevron.right' },
  body:
   { type: 2,
     start: 0,
     end: 13,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'chevron.right' } }  ... > 
  at <RouterLink key=0 ref_for=true to="/technologies"  ... > 
  at <LinkCollection class="ribbon-link" loading=false links= [ { title: { type: 0, start: 0, end: 13, loc: [Object], body: [Object] },
    url: '/technologies',
    icon: { name: [Object] } } ]  ... > 
  at <RibbonBar loading=false items= [ { description: { type: 0, start: 0, end: 27, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 44, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 65, loc: [Object], body: [Object] },
    links: [ [Object] ] } ] > 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>


 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol key=2 loading=false name= { type: 0,
  start: 0,
  end: 13,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 14, offset: 13 },
     source: 'chevron.right' },
  body:
   { type: 2,
     start: 0,
     end: 13,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'chevron.right' } }  ... > 
  at <LinkCollection class="ribbon-link" loading=false links= [ { title: { type: 0, start: 0, end: 13, loc: [Object], body: [Object] },
    url:
     'https://github.com/JonathanXDR/Application-Website-Frontend/compare/v3.0.6...v3.0.7',
    icon: { name: [Object] } } ]  ... > 
  at <RibbonBar loading=false items= [ { description: { type: 0, start: 0, end: 27, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 44, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 65, loc: [Object], body: [Object] },
    links: [ [Object] ] } ] > 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>


 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol key=2 loading=false name= { type: 0,
  start: 0,
  end: 13,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 14, offset: 13 },
     source: 'chevron.right' },
  body:
   { type: 2,
     start: 0,
     end: 13,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'chevron.right' } }  ... > 
  at <RouterLink key=0 ref_for=true to="/projects"  ... > 
  at <LinkCollection class="ribbon-link" loading=false links= [ { title: { type: 0, start: 0, end: 13, loc: [Object], body: [Object] },
    url: '/projects',
    icon: { name: [Object] } } ]  ... > 
  at <RibbonBar loading=false items= [ { description: { type: 0, start: 0, end: 27, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 44, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 65, loc: [Object], body: [Object] },
    links: [ [Object] ] } ] > 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>


 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol name= { type: 0,
  start: 0,
  end: 12,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 13, offset: 12 },
     source: 'sun.max.fill' },
  body:
   { type: 2,
     start: 0,
     end: 12,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'sun.max.fill' } } class="icon icon-large" > 
  at <SegmentNav items= [ { id: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 6, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } } ] gap="5px" component-size="xsmall"  ... > 
  at <NavBar> 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>


 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol name= { type: 0,
  start: 0,
  end: 9,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 10, offset: 9 },
     source: 'moon.fill' },
  body:
   { type: 2,
     start: 0,
     end: 9,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'moon.fill' } } class="icon icon-large" > 
  at <SegmentNav items= [ { id: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 6, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } } ] gap="5px" component-size="xsmall"  ... > 
  at <NavBar> 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>


 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol name= { type: 0,
  start: 0,
  end: 22,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 23, offset: 22 },
     source: 'circle.lefthalf.filled' },
  body:
   { type: 2,
     start: 0,
     end: 22,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'circle.lefthalf.filled' } } class="icon icon-large" > 
  at <SegmentNav items= [ { id: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 6, loc: [Object], body: [Object] },
    icon: { name: [Object] } },
  { id: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    category: { type: 0, start: 0, end: 5, loc: [Object], body: [Object] },
    label: { type: 0, start: 0, end: 4, loc: [Object], body: [Object] },
    icon: { name: [Object] } } ] gap="5px" component-size="xsmall"  ... > 
  at <NavBar> 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>


 WARN  [Icon] failed to load icon fa6-[object Object]:[object Object]


 WARN  [Icon] failed to load icon fa6-[object Object]:[object Object]


 WARN  [Icon] failed to load icon fa6-[object Object]:[object Object]


 WARN  [Icon] failed to load icon fa6-[object Object]:[object Object]


 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol key=2 loading=false name= { type: 0,
  start: 0,
  end: 13,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 14, offset: 13 },
     source: 'chevron.right' },
  body:
   { type: 2,
     start: 0,
     end: 13,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'chevron.right' } }  ... > 
  at <RouterLink key=0 ref_for=true to="/technologies"  ... > 
  at <LinkCollection class="ribbon-link" loading=false links= [ { title: { type: 0, start: 0, end: 13, loc: [Object], body: [Object] },
    url: '/technologies',
    icon: { name: [Object] } } ]  ... > 
  at <RibbonBar loading=false items= [ { description: { type: 0, start: 0, end: 27, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 44, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 65, loc: [Object], body: [Object] },
    links: [ [Object] ] } ] > 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>


 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol key=2 loading=false name= { type: 0,
  start: 0,
  end: 13,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 14, offset: 13 },
     source: 'chevron.right' },
  body:
   { type: 2,
     start: 0,
     end: 13,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'chevron.right' } }  ... > 
  at <LinkCollection class="ribbon-link" loading=false links= [ { title: { type: 0, start: 0, end: 13, loc: [Object], body: [Object] },
    url:
     'https://github.com/JonathanXDR/Application-Website-Frontend/compare/v3.0.6...v3.0.7',
    icon: { name: [Object] } } ]  ... > 
  at <RibbonBar loading=false items= [ { description: { type: 0, start: 0, end: 27, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 44, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 65, loc: [Object], body: [Object] },
    links: [ [Object] ] } ] > 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>


 WARN  [Vue warn]: Invalid prop: type check failed for prop "name". Expected String with value "[object Object]", got Object  
  at <SFSymbol key=2 loading=false name= { type: 0,
  start: 0,
  end: 13,
  loc:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 1, column: 14, offset: 13 },
     source: 'chevron.right' },
  body:
   { type: 2,
     start: 0,
     end: 13,
     loc: { start: [Object], end: [Object] },
     items: [ [Object] ],
     static: 'chevron.right' } }  ... > 
  at <RouterLink key=0 ref_for=true to="/projects"  ... > 
  at <LinkCollection class="ribbon-link" loading=false links= [ { title: { type: 0, start: 0, end: 13, loc: [Object], body: [Object] },
    url: '/projects',
    icon: { name: [Object] } } ]  ... > 
  at <RibbonBar loading=false items= [ { description: { type: 0, start: 0, end: 27, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 44, loc: [Object], body: [Object] },
    links: [ [Object] ] },
  { description: { type: 0, start: 0, end: 65, loc: [Object], body: [Object] },
    links: [ [Object] ] } ] > 
  at <Default ref=Ref< undefined > > 
  at <AsyncComponentWrapper ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        map: undefined,
        key: undefined,
        sc: 0,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App> 
  at <NuxtRoot>
```

**Comment by BobbieGoede** [comment]
The update from v8 to v9 also includes the move from vue-i18n v9 to v10 as dependency, which enabled the [JIT compiler by default](https://vue-i18n.intlify.dev/guide/migration/breaking10.html#default-enable-for-jit-compilation), that's why you're seeing an AST instead of strings.

The actual issue in your project is the usage of the `tm` function, I guess the previous usage (unexpectedly) worked due to messages still being regular objects, you should pass the values returned from `tm` into the `rt` function to make this work. See the [`tm(key)`](https://vue-i18n.intlify.dev/api/composition.html#tm-key) documentation and its example usage, this change occurred in vue-i18n v9.

Let me know if you have any questions! Closing this for now.

**Comment by JonathanXDR** [comment]
Hey @BobbieGoede, thanks again for your help! As far as I can tell from my testing, I now need to call `rt()` for **every** child object or nested text in my `tm()` results—basically recursing down wherever there’s translatable text. That means I’m writing something like:

```ts
const rawSections = computed(() => tm('some.key'))
const sections = computed(() =>
  rawSections.value.map((section) => ({
    ...section,
    label: rt(section.label),
    children: section.children?.map((child) => ({
      ...child,
      label: rt(child.label),
    }))
  }))
)
```

I just wanted to confirm: is there no simpler or automated way in Vue I18n v10 to handle this for deeply nested objects? It works fine, but if there’s a recommended pattern that’s less verbose, I’d love to know!

Thanks again!
