### ISSUE TITLE
Could not load @nuxtjs/i18n. Is it installed?

### ISSUE THREAD

**Issue by mendrinos** [nuxt-modules/i18n#3289]
### Environment

- Operating System: `Darwin`
- Node Version:     `v23.5.0`
- Nuxt Version:     `3.15.0`
- CLI Version:      `3.17.2`
- Nitro Version:    `2.10.4`
- Package Manager:  `yarn@4.6.0`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `@nuxtjs/i18n@9.1.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/sb1-wvuoha3x

### Describe the bug

`ERROR  Could not load @nuxtjs/i18n. Is it installed?                                                        11:06:06 PM

    at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2470:11)
    at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2388:67)
    at async initNuxt (node_modules/nuxt/dist/index.mjs:5275:5)
    at async loadNuxt (node_modules/nuxt/dist/index.mjs:5459:5)
    at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2640:19)
    at async Object.run (/Users/mendrinos/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/prepare.mjs:60:18)
    at async runCommand$1 (/Users/mendrinos/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.DSPrE7vg.mjs:1767:16)
    at async runCommand (/Users/mendrinos/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.DSPrE7vg.mjs:2138:10)
    at async Object.setup (/Users/mendrinos/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/add2.mjs:149:5)
    at async runCommand$1 (/Users/mendrinos/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.DSPrE7vg.mjs:1739:5)
    at async runCommand$1 (/Users/mendrinos/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.DSPrE7vg.mjs:1758:11)
    at async runCommand$1 (/Users/mendrinos/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.DSPrE7vg.mjs:1758:11)
    at async runMain$1 (/Users/mendrinos/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.DSPrE7vg.mjs:1896:7) 

 ERROR  Could not load @nuxtjs/i18n. Is it installed?                                                        11:06:06 PM
`

### Logs

```shell

```

**Comment by beesolutiondev** [comment]
Same issue here 

Node: v22.12.0
Same packges installed

**Comment by Tristwch** [comment]
> Same issue here
> 
> Node: v22.12.0 Same packges installed

I had the same.   node v22.9.0 | yarn | "nuxt": "^3.15.0"

yarn add vite typescript helped in my case

"typescript": "^5.7.2" | "vite": "^6.0.7"

**Comment by lukas-a-brand** [comment]
@Tristwch not sure you need Vite as explicit dependency, as nuxt 3.15.x adds Vite 6.
But adding typescript as dev dependency fixed it. Thanks for the hint. (:

**Comment by Navidkhm** [comment]
That is weird.
I had the same issue.
Installing typescript as dev dependencies worked but even without typescript when you try to install via NPM it works!!!
how?!

**Comment by BobbieGoede** [comment]
Some of the recent issues seem to only be present for projects using the `yarn` package manager, I'm not sure what the core issue/difference is 🤔

**Comment by Navidkhm** [comment]
> Some of the recent issues seem to only be present for projects using the `yarn` package manager, I'm not sure what the core issue/difference is 🤔

Exactly.
I can't guess what's going on to cause these types of issues.

**Comment by BobbieGoede** [comment]
I have found the source of this issue, it is caused upstream in `@intlify/unplugin-vue-i18n` (specifically https://github.com/intlify/bundle-tools/blob/pinned-deps-6-0-5/packages/unplugin-vue-i18n/src/core/directive.ts#L5-L10).

These dependencies require `typescript`, and just the presence of these imports are enough to trigger this issue, even when disabling the functionality (`bundle.optimizeTranslationDirective`) that makes use of those imports this issue persists. As to why this issue is exclusive to `yarn` is still a mystery to me... 🤔 

This functionality will be removed entirely in the future, but until then you can workaround this by explicitly adding `typescript` as a dependency as @Tristwch found (thank you 🙏).

I will look into fixing this from nuxt-i18n until we can update upstream (in nuxt-i18n v10 or even v11), it may be as simple as adding `typescript` as a prod dependency to ensure it is present when this module is installed.
